/* ============================================================
   VERBUM ORIGO — LESSONS (learning path, §5)
   Data-driven: every exercise references word ids, script
   entries or verse ids from the schema — no ad-hoc content.
   Exercise types: info | mcq | match | build | type | listen |
                   verse | tree
   ============================================================ */
(function(){
"use strict";
function L(id,lang,type,icon,title,subtitle,intro,ex){
  return { id:id, lang:lang, type:type, icon:icon, title:title, subtitle:subtitle, intro:intro||[], ex:ex||[] };
}
function M(pairs){ return {t:'match', pairs:pairs}; }
function MC(q,opts,a,why,wid){ return {t:'mcq', q:q, opts:opts, a:a, why:why||'', wid:wid||null}; }
function BD(prompt,answer,distract){ return {t:'build', prompt:prompt, answer:answer, distract:distract||[]}; }
function TY(prompt,accepts,placeholder){ return {t:'type', prompt:prompt, accepts:accepts, placeholder:placeholder||''}; }
function LS(wid,opts,why){ return {t:'listen', wid:wid, opts:opts, why:why||''}; }
function VER(vid){ return {t:'verse', vid:vid}; }
function TREE(vid){ return {t:'tree', vid:vid}; }

var LESSONS=[
L('heb-alph','heb','alphabet','א','Script & Alphabet','The 22 letters of Hebrew',
 [ "<h4>Right to left</h4>Hebrew reads <b>right&nbsp;to&nbsp;left</b>, like its cousin Aramaic. The 22 letters are the same ones that open Daniel and Ezra in Aramaic — and the ancestors of the square script used for Jewish and Arabic-descended scripts.",
   "<h4>Five final letters</h4>כ ך, מ ם, נ ן, פ ף, צ ץ — five letters take a special “closed” shape at the <i>end</i> of a word.",
   "<h4>Letters are pictures</h4>Each letter began as a simple picture: aleph = ox, bet = house, shin = tooth. The names survive in the English “alphabet.”"],
 [ MC('Which letter is this?  ש',['shin','samekh','ayin','qof'],0,'ש is <b>shin</b> (sh) — the “tooth.” The dot on the right makes it shin; on the left, sin (s).'),
   M([['he-aleph','ox (aleph)'],['he-bet','house (bet)'],['he-shin','tooth (shin)'],['he-lamed','goad (lamed)'],['he-mem','water (mem)'],['he-tav','mark (tav)']]),
   MC('At the <b>end</b> of a word, מ becomes…',['ם (final mem)','ך (final kaf)','ן (final nun)','ף (final pe)'],0,'מ → ם at word-end. The same rule gives כ→ך, נ→ן, פ→ף, צ→ץ.'),
   TY('Type the name of this letter:  ג',['gimel','gamel','gimel'], 'gimel'),
   MC('How many letters does the Hebrew alphabet have?',['22','24','26','18'],0,'22 — the same count as Aramaic.'),
   MC('This vowel sign ַ (patah) gives which sound?',['a (as in “cat”)','e (as in “bed”)','i (as in “bit”)','o (as in “boat”)'],0,'Patah = a. (Qamats ָ is a/o, segol ֶ is e, tsere ֵ is e/ai, hiriq ִ is i, holam ֹ is o, qubuts ֻ is u.)') ]),

L('heb-v1','heb','vocab','📜','The First Verse','Genesis 1:1 — seven words',
 [ "<h4>בְּרֵאשִׁית בָּרָא אֱלֹהִים</h4><div class='ex'>בְּרֵאשִׁית בָּרָא אֱלֹהִים אֵת הַשָּׁמַיִם וְאֵת הָאָרֶץ</div>“In the beginning God created the heavens and the earth.” Every word in this verse is a cornerstone of the Old Testament.",
   "<h4>How to read it</h4>Right to left. The small circle <b>ְ</b> (shva) is a light “uh” vowel; the horizontal line <b>ַ</b> is “a.” Tap any word in a verse study to open its full breakdown."],
 [ M([['w-heb-elohim','God'],['w-heb-bara','created'],['w-heb-shamayim','heavens'],['w-heb-aretz','earth'],['w-heb-reshit','beginning']]),
   BD('“God created the heavens and the earth”',['w-heb-elohim','w-heb-bara','w-heb-shamayim','w-heb-ve','w-heb-aretz'],['w-heb-or','w-heb-tob','w-heb-et']),
   MC('בָּרָא — how is this word parsed?',['Qal perfect, 3rd person masculine singular (“he created”)','Qal imperfect, 1st person (“I create”)','Piel perfect, 3rd feminine (“she created”)','Niphal perfect, 3rd masculine (“he was created”)'],0,'בָּרָא is Qal perfect 3ms — the completed action: “he created.”', 'w-heb-bara'),
   LS('w-heb-elohim',['w-heb-elohim','w-heb-adam','w-heb-or'],'That was אֱלֹהִים — “Elohim.”'),
   MC('What job does אֵת do in this verse?',['It marks the definite direct object','It means “and”','It negates the sentence','It makes a word plural'],0,'אֵת flags a definite object: God created THE heavens and THE earth. Aramaic does the same with יָת (yat).','w-heb-et'),
   MC('שָׁמַיִם (“heavens”) is unusual because it is…',['a dual form','always plural','feminine','never written with niqqud'],0,'A dual — like “two heavens” (the sky-firmament and the abode of God). Same with מַיִם (waters) and יָדַי (my hands).','w-heb-shamayim') ]),

L('heb-v2','heb','vocab','🕯️','Light & Voice','Genesis 1:3 — God speaks',
 [ "<h4>וַיֹּאמֶר אֱלֹהִים יְהִי אוֹר</h4><div class='ex'>וַיֹּאמֶר אֱלֹהִים יְהִי אוֹר וַיְהִי־אוֹר</div>“And God said, Let there be light: and there was light.” Creation happens by speech — the same idea as John 1:1 and Romans 10:8.",
   "<h4>Two verb tenses</h4>Hebrew verbs come in two great families: <b>perfect</b> (completed) and <b>imperfect</b> (incomplete). יְהִי “let there be” is a <b>jussive</b> — a short imperfect meaning “may it be!”"],
 [ M([['w-heb-or','light'],['w-heb-choshekh','darkness'],['w-heb-yom','day'],['w-heb-laylah','night'],['w-heb-tob','good']]),
   BD('“Let there be light”',['w-heb-hayah','w-heb-or'],['w-heb-amar','w-heb-elohim','w-heb-choshekh']),
   MC('וַיֹּאמֶר — the prefix וַ- before a verb marks…',['waw-consecutive (narrative “and he said”)','negation','the plural','a question'],0,'The narrative waw: וַ- + imperfect = “and he did…” — the engine of Hebrew storytelling.','w-heb-amar'),
   MC('Which word means “good”?',['טוֹב (tov)','אוֹר (or)','יוֹם (yom)','לֹא (lo)'],0,'טוֹב — “and God saw that it was good” is repeated through the creation week.','w-heb-tob'),
   LS('w-heb-or',['w-heb-or','w-heb-yom','w-heb-aretz'],'That was אוֹר — “light.”') ]),

L('heb-g1','heb','grammar','🧱','Nouns: Gender & Number','Feminine, masculine, and the dual',
 [ "<h4>Two genders</h4>Hebrew nouns are <b>masculine</b> or <b>feminine</b>. Most feminine singulars end in <b>-ah</b> (אֶרֶץ… cf. צְדָקָה), most masculine plurals in <b>-im</b> (אֲדָמִים).",
   "<h4>The dual</h4>Pairs get a special form: <b>-ayim</b> (שָׁמַיִם heavens, יָדַי my two hands, חַיִּים life)."],
 [ MC('שָׁמַיִם (heavens) is which number?',['Dual','Singular','Plural','Collective'],0,'The ending -ayim marks the dual.','w-heb-shamayim'),
   MC('Which of these is feminine singular?',['אֶרֶץ (earth)','שָׁמַיִם (heavens)','חַיִּים (life)','מַיִם (waters)'],0,'אֶרֶץ is feminine singular — one of the most common feminine nouns in the OT.','w-heb-aretz'),
   M([['w-heb-elohim','masc. plural'],['w-heb-aretz','fem. singular'],['w-heb-shamayim','masc. dual'],['w-heb-mayim','masc. dual'],['w-heb-adam','masc. singular'],['w-heb-emunah','fem. singular']]),
   TY('The common feminine plural ending is “-ot”. What is the common <b>masculine</b> plural ending? (letters only)',['im','ים'],'im') ]),

L('heb-g2','heb','grammar','⚖️','Verbs: Two Aspects','Perfect vs imperfect',
 [ "<h4>Completed vs incomplete</h4>Hebrew verbs split into <b>perfect</b> (qatal — completed, e.g. בָּרָא “he created”) and <b>imperfect</b> (yiqtol — incomplete, e.g. יִחְיֶה “he shall live”).",
   "<h4>Who is acting?</h4>Person + gender + number live in the endings: -ā (3ms), -îm (3mp), -î (1cs), -t (2ms), -t (2fs)…"],
 [ MC('יִחְיֶה — how is it parsed?',['Qal imperfect, 3rd masculine singular','Qal perfect, 3rd masculine singular','Qal imperfect, 1st common singular','Piel perfect, 3rd feminine singular'],0,'יִ-חְ-יֶ-ה = imperfect 3ms: “he shall live” (Hab 2:4).','w-heb-chayah'),
   MC('Which is the 1st person common singular imperfect (“I…”)?',['אֶחְסָר (I lack)','יִחְיֶה (he lives)','בָּרָא (he created)','תִּמְלֹא (she is filled)'],0,'אֶ-חְסָר = “I shall lack” — the psalmist’s word in Ps 23:1.','w-heb-chasar'),
   MC('בָּרָא — the stem “qal” means…',['simple, basic action','intensive/action on self','causing to happen','being acted upon'],0,'Qal is the simple active stem — the default: “he created.”','w-heb-bara'),
   MC('The form וַיְהִי (and there was) is…',['imperfect with narrative waw','perfect with conjunction','jussive','participle'],0,'וַ- + imperfect = narrative past: “and there was.”','w-heb-hayah') ]),

L('heb-v3','heb','vocab','🌊','Chaos & Spirit','Genesis 1:2 — the first theodrama',
 [ "<h4>וְהָאָרֶץ הָיְתָה תֹהוּ וָבֹהוּ</h4><div class='ex'>וְהָאָרֶץ הָיְתָה תֹהוּ וָבֹהוּ וְחֹשֶׁךְ עַל־פְּנֵי תְהוֹם וְרוּחַ אֱלֹהִים מְרַחֶפֶת עַל־פְּנֵי הַמָּיִם</div>“And the earth was without form and void; and darkness was upon the face of the deep. And the Spirit of God moved upon the face of the waters.” Verse 2 of the Bible — chaos, darkness, deep — and then, the hovering Spirit.",
   "<h4>A duet</h4>תֹהוּ (tohu, “formless”) and בֹהוּ (bohu, “void”) are a famous pair — <b>tohu wabohu</b>. The LXX splits them into two Greek adjectives: ἀόρμος (“without form”) and κενή (“empty”) — the same picture, two tongues."],
 [ M([['w-heb-tohu','formless'],['w-heb-bohu','void'],['w-heb-tehom','the deep'],['w-heb-choshekh','darkness'],['w-heb-ruach','spirit'],['w-heb-mayim','waters']]),
   MC('The pair תֹהוּ וָבֹהוּ means…',['without form and void','heaven and earth','light and darkness','king and priest'],0,'tohu wabohu — “formless and void.” The LXX says ἀόρμος καὶ κενή — “without form and empty.”','w-heb-tohu'),
   MC('מְרַחֶפֶת (merachefet) — “the Spirit …”',['hovers (Piel participle)','created (Qal perfect)','slept (Qal imperfect)','spoke (Piel participle)'],0,'Piel participle of רִחַף “to hover, skim” — once in all the OT, and the LXX matches it with ἐπεράζε “skimmeth.”','w-heb-rachaph'),
   MC('Which word does the LXX render as ἄβυσσος (“the abyss”)?',['t’ehom “the deep”','tohu “formless”','mayim “waters”','ruach “spirit”'],0,'t’ehom, “the deep,” is what the LXX calls ἄβυσσος — the word quoted again in Rom 10:9.','w-heb-tehom'),
   LS('w-heb-rachaph',['w-heb-rachaph','w-heb-bara','w-heb-ruach'],'That was מְרַחֶפֶת — the Spirit hovering, like a bird skimming the water.'),
   BD('“and the Spirit of God hovered”',['w-heb-ruach','w-heb-elohim','w-heb-rachaph'],['w-heb-or','w-heb-tohu','w-heb-tob']),
   VER('v-heb-gen-1-2'),
   TREE('v-heb-gen-1-2') ]),

L('heb-v4','heb','vocab','🐑','The Shepherd’s Song','Psalm 23 — the verb chain of care',
 [ "<h4>יְהוָה רֹעִי</h4><div class='ex'>יְהוָה רֹעִי לֹא אֶחְסָר · בִּנְאוֹת דֶּשֶׁא יַרְבִּיצֵנִי עַל־מֵימֵי מְנֻחוֹת יְנַחֵנִי · נַפְשִׁי יְשׁוֹבְבֶן מַעְגְּלֵי צֶדֶק יַנְחֵנִי לְמַעַן שְׁמוֹ</div>“The LORD is my shepherd; I shall not want. He maketh me to lie down in green pastures: he leadeth me beside the still waters. He restoreth my soul: he leadeth me in the paths of righteousness for his name’s sake.”",
   "<h4>Five Shepherd actions</h4>He <b>is</b> (יְהוָה רֹעִי), he <b>makes lie down</b> (יַרְבִּיצֵנִי), he <b>leads</b> (יְנַחֵנִי), he <b>restores</b> (יְשׁוֹבְבֶן), he <b>guides</b> (יַנְחֵנִי). The psalm is a chain of verbs — a whole theology of care."],
 [ M([['w-heb-roeh','shepherd (my)'],['w-heb-naot','pastures'],['w-heb-deshav','green grass'],['w-heb-rabats','he makes me lie down'],['w-heb-menuchah','still waters'],['w-heb-naphash','my soul']]),
   MC('יַרְבִּיצֵנִי is…',['Hiphil imperfect 3ms with 1sg suffix (“he makes ME lie down”)','Qal perfect 1cs','Piel passive','Pual participle'],0,'Hiphil is the causative stem: “he causes ME (‑enî) to lie down.” The shepherd does the making.','w-heb-rabats'),
   MC('צֶדֶק (tsedeq) and the familiar צְדָקָה (tsedeqah) are…',['two abstracts of the same root צדק (righteousness)','unrelated roots','the same word, misspelled','a noun and its verb'],0,'Both from the root צדק: tsedeq, the masculine abstract; tsedeqah, the feminine — one root, two abstracts.','w-heb-tsedeq'),
   MC('לְמַעַן שְׁמוֹ — “for his name’s sake” — the name here means…',['God’s honor and presence','a secret code word','the psalmist’s name','a list of God’s titles'],0,'The shem of God is his honored presence. The shepherd works for the name’s sake — covenant signature on the care.','w-heb-shem'),
   LS('w-heb-naphash',['w-heb-naphash','w-heb-ruach','w-heb-or'],'That was נַפְשִׁי — “my soul.”'),
   BD('“he leadeth me beside the still waters”',['w-heb-nachah','w-heb-al','w-heb-mayim','w-heb-menuchah'],['w-heb-naot','w-heb-or','w-heb-tob']),
   VER('v-heb-ps-23-2') ]),

L('heb-v5','heb','vocab','✨','Let There Be Light','Genesis 1:3-4 & Psalm 119:105',
 [ "<h4>וַיֹּאמֶר אֱלֹהִים לִמְהִי אוֹר</h4><div class='ex'>וַיֹּאמֶר אֱלֹהִים לִמְהִי אוֹר וַיְהִי אוֹר</div>“And God said, Let there be light: and there was light.” The jussive limhî — “let there be” — is the shortest creation engine in the Bible: a verb, and it is.",
   "<h4>Lamp and light</h4>Psalm 119:105 turns the cosmic light into a pocket lamp: “Your word is a LAMP (nēr) unto my feet, and a LIGHT (ʾôr) unto my path (maagalî).” The LXX keeps both: lampas and phōs. One family — light — in three tongues."],
 [ M([['w-heb-or','light'],['w-heb-ner','lamp'],['w-heb-rgal','my foot'],['w-heb-magal','my path'],['w-heb-l','to; unto'],['w-heb-rah','he saw']]),
   MC('לִמְהִי (limhî) — “let there be” — is which form?',['jussive of “to be”','perfect 3ms','imperfect 1cs','cohortative plural'],0,'The jussive: a verb of “letting be.” God says the word, and the light is.','w-heb-limhi'),
   MC('נֵר (nēr) and אוֹר (ʾôr) are…',['“lamp” (the object) and “light” (the substance)','the same word, two spellings','“fire” and “sun”','a noun and its plural'],0,'nēr is the lamp that holds it; ʾôr is the light itself. The LXX keeps the pair: lampas + phōs; the Vulgate: lumen + lux.','w-heb-ner'),
   MC('מַעְגָּלִי (maagalî, “my path”) is the SAME root as which Psalm 23 word?',['maagalei — “paths” (Ps 23:3)','roeh — “shepherd”','menuchot — “rest”','deshav — “grass”'],0,'From עגל “to circle”: life as a right-circled walk — Ps 23:3 and Ps 119:105 share the root.','w-heb-magal'),
   LS('w-heb-ner',['w-heb-ner','w-heb-or','w-heb-magal'],'That was נֵר — the lamp of the temple courts, and of the word.'),
   BD('“your word is a lamp unto my feet”',['w-heb-davar','w-heb-ner','w-heb-l','w-heb-rgal'],['w-heb-or','w-heb-magal','w-heb-tob']),
   VER('v-heb-gen-1-3'),
   VER('v-heb-ps-119-105') ]),

L('heb-v6','heb','vocab','🦅','Wings Like Eagles','Isaiah 40:31 — the strength exchange',
 [ "<h4>כִּי יָגוּ יַחֲלוּ</h4><div class='ex'>כִּי יָגוּ בְיְהוָה יַחֲלוּ כֹחַ יַרְחִפוּ כַּאֵילִים יִרְצוּ וְלֹא יִכְלֶה וְהָלְכוּ וְלֹא יָעֵפוּ</div>“But they that wait upon the LORD shall renew their strength; they shall mount up with wings, as eagles; they shall run, and not be weary; and they shall walk, and not faint.”",
   "<h4>Four pictures, one promise</h4>Soar (yarḥîpû — the same root as the hovering Spirit of Gen 1:2!), run, walk — and three negations: not weary, not spent, not faint. Waiting is not standing still; it is changing the source of the strength."],
 [ M([['w-heb-yagu','they wait'],['w-heb-yachalu','renew strength'],['w-heb-yarhipu','they soar'],['w-heb-kanaf','wings'],['w-heb-ayit','eagles'],['w-heb-yirtsa','they run']]),
   MC('יַרְחִפוּ “they shall mount up” is built from the SAME root as which Genesis 1:2 word?',['merachefet — the hovering Spirit','bara — created','ruach — spirit','mayim — waters'],0,'The רחפ of the hovering Spirit becomes the soar of the eagle: the same root, from skimming to lifting.','w-heb-yarhipu'),
   MC('יַחֲלוּ “shall renew their strength” is…',['Polel imperfect — a change of state','Qal perfect — done long ago','Hiphil — made by someone else','Niphal — passive'],0,'Polel of ḥālal “be strong”: not adding fuel to old fire, but exchanging the fuel — the strength itself changes.','w-heb-yachalu'),
   MC('The three negations of the verse are…',['lo yikhleh · lo ya’efu (and lo before both)','two negations only','one negation, repeated','negated with mē'],0,'“Not be weary, not be spent, not faint” — the promise is written in negations: what will NOT happen.','w-heb-yikhleh'),
   LS('w-heb-kanaf',['w-heb-kanaf','w-heb-ayit','w-heb-yarhipu'],'That was כַּנְפֵי — wings: the shelter of Ps 91 and the soaring of Isaiah 40.'),
   BD('“they shall mount up with wings as eagles”',['w-heb-yarhipu','w-heb-kanaf','w-heb-kaf','w-heb-ayit'],['w-heb-yirtsa','w-heb-yagu','w-heb-yachalu']),
   VER('v-heb-isa-40-31') ]),

L('heb-g3','heb','grammar','🗣️','Vowels: Six Points','Niqqud — the six vowel signs',
 [ "<h4>Letters are consonants</h4>Hebrew writes its consonants bare; the small dots and lines under and over them are <b>vowels</b>: hiriq ִ (i), tsere ֵ (e/ai), segol ֶ (e), patah ַ (a), qamats ָ (a/o), holam ֹ (o). Learn the six, and the whole Pentateuch opens.",
   "<h4>Two helpers</h4>The shva ְ is a light “uh” (or a pause-mark); the dagesh, a dot inside a letter, doubles it or hardens it. Together with the six vowels they carry every word you will ever read."],
 [ MC('The sign ִ (a single dot below) is…',['hiriq — the “i” sound','qamats — the “a” sound','holam — the “o” sound (it sits above)','shva — the light “uh”'],0,'Hiriq: one dot below = i (as in “bit”). Remember: the holam sits ABOVE the letter, like a hat.','w-heb-mayim'),
   MC('The sign ָ (a line below) is…',['qamats — the “a” (or long o) sound','patah — the “a” sound (it is a triangle)','tsere — the “e” sound','holam — the “o” sound'],0,'Qamats: the line below = a (as in “father”). Patah is the little triangle: also a.','w-heb-yom'),
   MC('In אוֹר (ʾôr, “light”) the dot is ABOVE the vav — that is…',['holam — “o”','qamats — “a”','hiriq — “i”','segol — “e”'],0,'Hiram… no — holam! The dot above is holam, the “o” vowel: ʾôr, light.','w-heb-or'),
   MC('In מָיִם (mayim, “waters”) the dot after the yod is…',['hiriq (i)','patah (a)','holam (o)','tsere (e)'],0,'mayIM — hiriq gives the “i.” The line below the mem is qamats: mayim, the dual-ghost of water.','w-heb-mayim'),
   M([['w-heb-or','holam (o)'],['w-heb-yom','qamats (a)'],['w-heb-shem','segol (e)'],['w-heb-mayim','hiriq (i)'],['w-heb-laylah','tsere + qamats'],['w-heb-davar','qamats (a)']]),
   TY('Type the name of the vowel that gives אוֹר its “o” sound',['holam','holam','holam-vav'],'holam'),
   LS('w-heb-yom',['w-heb-yom','w-heb-or','w-heb-shem'],'That was יוֹם — day. Listen for the qamats: the long “a.”') ]),

L('heb-g4','heb','grammar','🧲','The Little Words','al · l · et · ve · ke — five glue words',
 [ "<h4>Five words hold the OT up</h4>al (upon, over), l (to, for), et (the direct-object mark), ve (and, now, but), ke (like, as). None of them has a “translation” that never changes — but every verse uses them.",
   "<h4>et — the finger</h4>et has no meaning of its own; it points: “THIS is the thing acted upon.” God did not merely create — he created <b>ET ha-shamayim</b>, the heavens, precisely."],
 [ MC('אֵת (et) before a noun marks…',['the direct object (“the thing acted upon”)','possession (“of”)','location (“in”)','time (“when”)'],0,'et is the finger of the verb: God created ET shamayim — the heavens, the very object of the creating.','w-heb-et'),
   MC('וְ (ve) can mean “and” — but also…',['“now” or “but” (the great conjunction of narrative)','only “or”','a question word','a preposition “to”'],0,'One letter, three moods: and / now / but. Half the drama of the Bible rides on ve.','w-heb-ve'),
   MC('כְּ (ke) in “wings, AS eagles” (Isa 40:31) is…',['the comparison preposition “like, as”','the direct-object mark','a past-tense sign','the name of God'],0,'ke = like: the Hebrew of simile. kāʾêlîm — “like eagles.”','w-heb-kaf'),
   MC('עַל (al) in Gen 1:2 — “upon the face of the deep” — is answered in Greek by…',['epi (“upon”) — the fam-epi family','en (“in”)','eis (“into”)','pros (“toward”)'],0,'al · epi · super — one “upon” in three tongues: the fam-epi family.','w-heb-al'),
   M([['w-heb-al','upon; over'],['w-heb-l','to; for; unto'],['w-heb-et','the (direct-object mark)'],['w-heb-ve','and; now; but'],['w-heb-kaf','like; as']]),
   BD('“a lamp unto my feet”',['w-heb-ner','w-heb-l','w-heb-rgal'],['w-heb-al','w-heb-or','w-heb-magal']),
   LS('w-heb-al',['w-heb-al','w-heb-l','w-heb-kaf'],'That was עַל — the preposition of “above,” three tongues deep.') ]),

L('heb-g5','heb','grammar','⚙️','Causative Stems','Hiphil & Piel — the doer and the maker',
 [ "<h4>One root, many engines</h4>Hebrew verbs wear <b>stems</b>. Qal does the plain action; Hiphil makes it happen (causative); Piel works it intensely; Polel, a rare cousin, intensifies too. רָבַץ “lie down” becomes יַרְבִּיצֵנִי — “he MAKES me lie down.”",
   "<h4>The Shepherd’s stems</h4>Psalm 23 runs on them: yarbîṣênî (Hiphil — he makes me lie down), yanĥēnî (Piel — he leads), yeshōbbên (Piel — he restores). And Isa 40:31’s soaring — yarḥîpû — wears the SAME root as the hovering Spirit of Gen 1:2."],
 [ MC('יַרְבִּיצֵנִי (Ps 23:2) is…',['Hiphil of רָבַץ — “he makes ME lie down”','Qal perfect 1cs','Piel passive','Niphal — “I am lying down”'],0,'Hiphil = causative: the shepherd does the making. The 1sg suffix ‑enî: he makes ME.','w-heb-rabats'),
   MC('Piel is best described as…',['the intensive / active-work stem','the plain Qal stem','a past-tense marker','the stem of adverbs'],0,'Piel works the verb harder: restore (not merely return), lead (not merely walk beside).','w-heb-nachah'),
   MC('יְשׁוֹבְבֶן “he restores” (Ps 23:3) is the Piel of…',['שׁוּב — “to return”','חָלַה — “to be strong”','רָחַף — “to hover”','לָכַך — “to walk”'],0,'shuv = to return; the Piel turns returning into RESTORING: the soul is brought back, not merely mended.','w-heb-shuv'),
   MC('יַרְחִפוּ “they shall soar” (Isa 40:31) shares its root with…',['מְרַחֶפֶת — the hovering Spirit (Gen 1:2)','בָּרָא — created','יָחֲלוּ — they shall be strong','עָגַל — to circle'],0,'The רחפ of the hovering becomes the soar of the eagle: one root, from skimming to lifting.','w-heb-yarhipu'),
   M([['w-heb-rabats','Hiphil: makes lie down'],['w-heb-nachah','Piel: leads'],['w-heb-shuv','Piel: restores'],['w-heb-yarhipu','Polel: soars'],['w-heb-yachalu','Polel: make strong']]),
   BD('“he leadeth me beside the still waters”',['w-heb-nachah','w-heb-al','w-heb-mayim','w-heb-menuchah'],['w-heb-rabats','w-heb-shuv','w-heb-or']),
   LS('w-heb-yarhipu',['w-heb-yarhipu','w-heb-rachaph','w-heb-kanaf'],'That was יַרְחִפוּ — the hover became the soar.') ]),

L('heb-v7','heb','vocab','📜','The Vision','Habakkuk 2:4 — nine words, two Testaments',
 [ "<h4>חָזֵה הַגָּאֵב…</h4><div class='ex'>חָזֵה הַגָּאֵב כִּי־לֹא יְשָׁר נַפְשׁוֹ בּוֹ וְהַצַּדִּיק בְּצִדְקָתוֹ יִחְיֶה</div>“Behold, the proud, his soul is not upright in him: but the righteous shall live by his faith.” Nine words carry the whole book — and both Testaments quote them (Rom 1:17, Heb 10:38, James 2:23).",
   "<h4>A mirror verse</h4>The dead-sea variant keeps the same picture in balance: the proud one (gaev) whose soul (naphash) is not upright — and the tsaddiq who lives (chayah) by faith (emunah). Pride and faith, weighed on the same scale."],
 [ M([['w-heb-tsaddiq','the righteous one'],['w-heb-tsedeqah','righteousness (his)'],['w-heb-emunah','faith; faithfulness'],['w-heb-chayah','he shall live'],['w-heb-hineh','behold'],['w-heb-gaev','the proud one']]),
   MC('צְדָקָתוֹ (ṣidqāṯô) appears twice in the verse. The second time it means…',['“IN his righteousness” (the basis of his life)','“against his righteousness”','“his two righteousnesses”','“the righteousness of all”'],0,'bĕṣidqatô — “by/in his righteousness.” One root צדק wearing the feminine abstract, twice in one verse.','w-heb-tsedeqah'),
   MC('יִחְיֶה (yĕḥyeh, “shall live”) is built from…',['the root of חַיָּה / חַיִּים — “life”','a root for “sleep”','the root of choshekh','a verb of eating'],0,'chāyah → ḥay / ḥayyîm: to live, life, the living. The righteous one’s verb is LIFE itself.','w-heb-chayah'),
   MC('אֱמוּנָה (emunah) in this verse means…',['faith AND faithfulness — one word, both sides','only “opinion”','a list of commandments','a festival name'],0,'emunah grips both ways: trust in God, and faithfulness to him. The LXX answers it with pistis; the Vulgate, fides.','w-heb-emunah'),
   LS('w-heb-emunah',['w-heb-emunah','w-heb-tsaddiq','w-heb-chayah'],'That was אֱמוּנָה — faith, the word that outlived the prophet.'),
   BD('“but the righteous shall live by his faith”',['w-heb-ve','w-heb-tsaddiq','w-heb-chayah','w-heb-tsedeqah'],['w-heb-gaev','w-heb-hineh','w-heb-naphash']),
   VER('v-heb-hab-2-4') ]),

L('heb-v8','heb','vocab','⚖️','One Root, Three Faces','tsedeq · tsedeqah · tsaddiq',
 [ "<h4>צֶדֶק · צְדָקָה · צַדִּיק</h4><div class='ex'>צֶדֶק · צְדָקָה · צַדִּיק</div>One root (צדק) gives three faces: the QUALITY (tsedeq, masculine abstract), the QUALITY in feminine dress (tsedeqah), and the PERSON who wears it (tsaddiq, “the righteous one”).",
   "<h4>Where they meet</h4>tsedeq walks the paths of Ps 23:3; tsedeqah is weighed in Hab 2:4; tsaddiq is the man both verses are about. Master the three, and a hundred verses stop being strangers."],
 [ MC('Which is the PERSON — “the righteous one”?',['tsaddiq (צַדִּיק)','tsedeq (צֶדֶק)','tsedeqah (צְדָקָה)','emunah (אֱמוּנָה)'],0,'tsaddiq — the adjective-turned-person: the one whose walking IS the quality.','w-heb-tsaddiq'),
   MC('The FEMININE abstract of צדק is…',['tsedeqah (צְדָקָה)','tsedeq (masculine abstract)','tsaddiq (the person)','chasad (mercy)'],0,'The ‑ah ending marks the feminine abstract: ṣidqāh, “righteousness” with the feminine coat on.','w-heb-tsedeqah'),
   MC('צֶדֶק (tsedeq) in “paths of righteousness” is…',['the masculine abstract noun','the person','the feminine noun','a verb'],0,'ṣedeq — masculine abstract: the “paths of ṣedeq,” Ps 23:3. Same root as the tsaddiq of Hab 2:4.','w-heb-tsedeq'),
   MC('The SAME root runs through which two verses?',['Ps 23:3 (tsedeq) + Hab 2:4 (tsedeqah/tsaddiq)','Gen 1:1 + Ps 23:1','Isa 40:31 + Jhn 8:12','Ps 119:105 + Ps 23:2'],0,'צדק threads the Shepherd (paths of tsedeq) and the Prophet (the tsaddiq lives by faith). One root, a whole theology.','w-heb-tsedeqah'),
   TY('Type the transliteration of “the righteous one”',['tsaddiq','tsaddiq','tzaddiq'],'tsaddiq'),
   M([['w-heb-tsedeq','the quality (masc.)'],['w-heb-tsedeqah','the quality (fem.)'],['w-heb-tsaddiq','the person'],['w-heb-agalah','paths (Ps 23:3)'],['w-heb-emunah','faith (Hab 2:4)'],['w-heb-chayah','shall live (Hab 2:4)']]),
   LS('w-heb-tsedeq',['w-heb-tsedeq','w-heb-tsedeqah','w-heb-tsaddiq'],'That was צֶדֶק — the quality itself, walking in paths.') ]),

L('heb-v9','heb','vocab','🌗','Day & Night','or · choshekh · yom · laylah — the first clock',
 [ "<h4>Light, darkness, day, night</h4><div class='ex'>אוֹר · חֹשֶׁךְ · יוֹם · לַיְלָה</div>Four words set the first clock of the Bible: ʾôr (light), ḥoshekh (darkness), yôm (day), laylâ (night). God names the light Day and the darkness Night — naming as an act of order.",
   "<h4>The family of darkness</h4>ḥoshekh answers Greek skotia (Jhn 1:5: “the light shineth in darkness”) and Latin… the dark that the light does not defeat. One darkness, three tongues, one verdict."],
 [ M([['w-heb-or','light'],['w-heb-choshekh','darkness'],['w-heb-yom','day'],['w-heb-laylah','night'],['w-heb-hayah','was'],['w-heb-ve','and']]),
   MC('חֹשֶׁךְ (ḥoshekh, “darkness”) is the Hebrew family-member of…',['Greek skotia (Jhn 1:5)','Greek phōs (light)','Latin lux','Aramaic shamaya'],0,'ḥoshekh · skotia · skotos — the darkness family across the whole Bible: Gen 1:2, Jhn 1:5, LXX Gen 1:2.','w-heb-choshekh'),
   MC('In the creation account, yôm and laylâ are…',['masculine “day” and feminine “night”','both masculine','both feminine','two words for “morning”'],0,'yôm (masc.) — the day; laylâ (fem.) — the night. The evening, erev, opens each “day” of the first week.','w-heb-yom'),
   MC('“And God called the light Day” — the light received a NAME, which is…',['yôm — “day”','nēr — “lamp”','ʾôr — “light” (again)','shem — “name”'],0,'The light was already ʾôr; its NAME became yôm. To name is to order: the clock starts.','w-heb-yom'),
   BD('“and there was light”',['w-heb-hayah','w-heb-or'],['w-heb-choshekh','w-heb-yom','w-heb-laylah']),
   LS('w-heb-choshekh',['w-heb-choshekh','w-heb-or','w-heb-laylah'],'That was חֹשֶׁךְ — the darkness that never won.'),
   VER('v-heb-gen-1-3') ]),

L('grc-alph','grc-nt','alphabet','Ω','Script & Alphabet','24 letters + accents',
 [ "<h4>24 letters</h4>Greek reads left to right. The NT is written in a 24-letter alphabet — many of its letters came to us via Greek.",
   "<h4>Two vowels per sound</h4>α and ο are “short”; ε → ει (long e), ο → ω (long o), ι → υ (y/i). In New Testament Greek, <b>η</b> says long “e.”",
   "<h4>Accents & breathings</h4>The <b>rough breathing</b> (῾) marks the “h” of θ, φ, χ… wait — of <b>initial h-sounds</b> (θεός has one). The <b>acute</b> (´), <b>grave</b> (`) and <b>circumflex</b> (ˆ) mark the stressed syllable."],
 [ M([['gr-alpha','alpha'],['gr-beta','beta'],['gr-gamma','gamma'],['gr-sigma','sigma'],['gr-omega','omega'],['gr-theta','theta']]),
   MC('How many letters are in the Greek alphabet?',['24','22','26','20'],0,'24 — from alpha to omega.'),
   MC('At the <b>end</b> of a word, sigma looks like…',['ς','σ','Σ','ξ'],0,'Final sigma (ς) — that’s why ἦν ends “-ν” with a smooth last sigma… (σ mid-word, ς final).'),
   TY('Type the name of this letter:  λ',['lambda'],'lambda'),
   MC('θεός carries a rough breathing at the start. It marks…',['an “h” sound (th in “theos”)','stress on the last syllable','a long vowel','negation'],0,'The rough breathing is the ancient “h” — θεός was once pronounced like “théos.”'),
   MC('Which letter says the “ph” in “phone” / “Philip” / “phos”?',['φ (phi)','θ (theta)','χ (chi)','ψ (psi)'],0,'φ = ph — light, phōs, Philip, philosophy all begin with it.') ]),

L('grc-v1','grc-nt','vocab','Λ','The Word','John 1:1 in Koine',
 [ "<h4>Ἐν ἀρχῇ ἦν ὁ λόγος</h4><div class='ex'>Ἐν ἀρχῇ ἦν ὁ λόγος, καὶ ὁ λόγος ἦν πρὸς τὸν θεόν, καὶ θεὸς ἦν ὁ λόγος.</div>“In the beginning was the Word, and the Word was with God, and the Word was God.” The most grammar-packed sentence in the NT — and the LXX’s opening of Genesis 1:1 is the same template: ἐν ἀρχῇ.",
   "<h4>Watch the article</h4>ὁ/τὸν = “the” (masc.). Its absence is meaningful: the final θεός has NO article — it predicates a quality: “<i>divine</i> was the Word.”"],
 [ M([['w-grc-logos','word'],['w-grc-theos','God'],['w-grc-archi','beginning'],['w-grc-eimi','to be'],['w-grc-kai','and']]),
   BD('“In the beginning was the Word”',['w-grc-en','w-grc-archi','w-grc-eimi','w-grc-logos'],['w-grc-theos','w-grc-pros','w-grc-kai']),
   BD('“the Word was God”',['w-grc-logos','w-grc-eimi','w-grc-theos'],['w-grc-art-ho','w-grc-art-ton']),
   MC('In “θεὸς ἦν ὁ λόγος,” the final θεός has no article. This expresses…',['a predicate quality (“God was the Word”)','a definite subject','a vocative (“O God”)','a genitive'],0,'Without the article, θεός describes WHAT the Word was — divine in nature. Compare “Moses was a prophet” (anarthrous) in John 1:21.','w-grc-theos'),
   LS('w-grc-logos',['w-grc-logos','w-grc-theos','w-grc-phos'],'That was λόγος — “the Word.”'),
   MC('ἀρχή (beginning) is the LXX’s rendering of Hebrew…',['בְּרֵאשִׁית (bereshit)','דָּבָר (davar)','אוֹר (or)','רֹאשׁ (rosh)'],0,'LXX Gen 1:1 = ἐν ἀρχῇ ἐποίησεν ὁ θεός… — the same “in the beginning” as the Hebrew.' ) ]),

L('grc-v2','grc-nt','vocab','💗','The Love','John 3:16 in Koine',
 [ "<h4>ὅτι οὕτως ἠγάπησεν ὁ θεὸς τὸν κόσμον</h4><div class='ex'>ὅτι οὕτως ἠγάπησεν ὁ θεὸς τὸν κόσμον, ὥστε τὸν υἱὸν αὐτοῦ τὸν μονογενῆ δώσειν…</div>“For God so loved the world, that he gave his only begotten Son…”",
   "<h4>Three special verb forms</h4>ἠγάπησεν = <b>aorist</b> (simple past). δώσειν = <b>aorist infinitive</b> (“to give”). πιστεύων = <b>present participle</b> (“believing”) — the NT loves its participles."],
 [ M([['w-grc-hagapeo','to love'],['w-grc-kosmos','world'],['w-grc-huios','son'],['w-grc-pisteuo','to believe'],['w-grc-zoe','life']]),
   BD('“God so loved the world”',['w-grc-theos','w-grc-hagapeo','w-grc-kosmos'],['w-grc-art-ho','w-grc-zoe','w-grc-kai']),
   MC('ἠγάπησεν is which tense of ἀγαπάω?',['Aorist (“loved” — a single complete act)','Present (“loves”)','Imperfect (“was loving”)','Future (“will love”)'],0,'Aorist indicative 3sg — the completed act of love that triggers everything else in the verse.','w-grc-hagapeo'),
   MC('πιστεύων (“believing”) is a…',['present active participle','aorist infinitive','perfect passive verb','present subjunctive'],0,'A participle — a verb acting as an adjective: “everyone believing” = “everyone who believes.”','w-grc-pisteuo'),
   MC('δώσειν in this verse means…',['“to give” (aorist infinitive)','“given” (past)','“giving now” (present)','“he will give” (future)'],0,'Aorist active infinitive after ὥστε — “so that… to give.”','w-grc-didomi') ]),

L('grc-g1','grc-nt','grammar','📐','Nouns & Cases','Five cases, endings tell',
 [ "<h4>Cases, not prepositions</h4>Greek marks a noun’s role with its <b>ending</b>: nominative (subject), genitive (of), dative (to/with), accusative (direct object), vocative (O…).",
   "<h4>Two big declensions</h4>1st declension (mostly -ης, feminine): ἀρχή → ἀρχῇ (dat.), ἀρχήν (acc.). 2nd declension (-ος, m/n): λόγος → λόγου (gen.), λόγῳ (dat.), λόγον (acc.)."],
 [ MC('ἀρχῇ (in John 1:1) is which case?',['Dative','Accusative','Genitive','Nominative'],0,'-ῃ marks the dative of 1st-declension feminine nouns — “in the beginning.”','w-grc-archi'),
   MC('θεόν (in “with God”) is which case?',['Accusative','Nominative','Dative','Vocative'],0,'-όν after πρὸς: the preposition πρὸς takes the accusative.','w-grc-theos'),
   MC('Which case does the preposition εἰς take?',['Accusative','Dative','Genitive','Ablative'],0,'εἰς + acc. = “into / toward.” “Believe IN him” = εἰς αὐτόν.','w-grc-eis'),
   M([['w-grc-logos','nominative: λόγος'],['w-grc-kosmos','accusative: κόσμον'],['w-grc-archi','dative: ἀρχῇ'],['w-grc-hemera','genitive: ἡμέρας']]),
   MC('Which of these is a vocative (direct address)?',['Πατέρα (O Father!)','ἡ ἡμέρα (the day)','τὸ πνεῦμα (the spirit)','ἐν ἀρχῇ (in the beginning)'],0,'The vocative is for calling someone: Πατέρα — as in “Pater noster” = Πατὴρ ἡμῶν, “O our Father.”') ]),

L('grc-g2','grc-nt','grammar','⏳','Verbs & Tenses','Aspect, not just time',
 [ "<h4>Greek verbs encode aspect</h4><b>Present</b> = ongoing (ἔχω “I have/am holding”), <b>aorist</b> = simple completed act (ἠγάπησεν “loved”), <b>imperfect</b> = ongoing in the past (ἦν “was being”), <b>perfect</b> = completed with lasting results.",
   "<h4>Moods</h4>Indicative states facts (ἦν “was”), subjunctive aims at the unknown (ἔχῃ “may have” — purpose clauses), infinitive is the “verb as noun” (δώσειν “to give”)."],
 [ MC('ἦν in John 1:1 is the…',['imperfect of εἰμί (“was” — ongoing state)','aorist of εἰμί','perfect of εἰμί','present of γίνομαι'],0,'Imperfect 3sg: continuous being — “the Word WAS (continually) God.”','w-grc-eimi'),
   MC('ἔχῃ in John 3:16 is which mood?',['Present subjunctive (“may have”)','Present indicative','Aorist indicative','Perfect subjunctive'],0,'Subjunctive of purpose: “that he MAY HAVE eternal life.”','w-grc-echo'),
   MC('Which word is a participle?',['πιστεύων','ἔπεσεν','δώσειν','ἦν'],0,'-ων marks the present active participle: “believing.”','w-grc-pisteuo'),
   MC('δώσειν is…',['an aorist infinitive (“to give”)','a present participle','an aorist imperative','a perfect verb'],0,'The -σειν ending: aorist active infinitive.') ]),

L('grc-v3','grc-nt','vocab','☀️','Light of the World','Matthew 5:14 & John 1:5',
 [ "<h4>ὑμεῖς ἐσθέ τὸ φῶς</h4><div class='ex'>ὑμεῖς ἐσθέ τὸ φῶς τοῦ κόσμου · τὸ φῶς ἐν τῇ σκοτίᾳ λαμπέι· καὶ ἡ σκοτία αὐτὸ οὐ κατέλαβεν</div>“Ye are the light of the world” (Matt 5:14). And John’s prologue: “And the light shineth in darkness; and the darkness comprehended it not” (Jhn 1:5). One light, two witnesses.",
   "<h4>Articles do the work</h4>τὸ φῶς — “THE light.” The Greek article (ὁ / ἡ / τό) does the work of English “the”; drop it, and the verse loses its weight."],
 [ M([['w-grc-hymeis','you (pl.)'],['w-grc-este','you are'],['w-grc-phos','light'],['w-grc-kosmos','world'],['w-grc-skotia','darkness'],['w-grc-lampo','it shines']]),
   MC('ὑμεῖς ἐσθέ — “you are” — is which person and number?',['2nd person plural','1st person singular','3rd person plural','2nd person singular'],0,'hymeis esté — the “you” of the Sermon on the Mount. An identity call: you ARE light.','w-grc-este'),
   MC('In “τὸ φῶς τοῦ κόσμου,” τοῦ is…',['the genitive article (“of the”)','a noun meaning “head”','a 2nd-person pronoun','an adverb (“now”)'],0,'tou is the genitive of the article: “light OF the world.”','w-grc-tou'),
   MC('οὐ κατέλαβεν — “comprehended it not” — the negation οὐ…',['negates indicative statements (cf. Hebrew lōʾ, Latin non)','negates subjunctives (that is mē)','is a preposition “outside”','is an interjection “oh”'],0,'ou is the “not” of statements — kin of Hebrew lōʾ and Latin non. (mē belongs to subjunctive moods.)','w-grc-ou'),
   LS('w-grc-lampo',['w-grc-lampo','w-grc-kosmos','w-grc-phos'],'That was λαμπέι — “it shines.”'),
   BD('“and the darkness comprehended it not”',['w-grc-kai','w-grc-e','w-grc-skotia','w-grc-auto','w-grc-ou','w-grc-katalaben'],['w-grc-phos','w-grc-este','w-grc-hymeis']),
   VER('v-grc-mat-5-14'),
   VER('v-grc-jhn-1-5') ]),

L('grc-v4','grc-nt','vocab','🕯️','I Am the Light','John 8:12 — the light of life',
 [ "<h4>ΕΓΩ ΕΙΜΙ ΤΟ ΦΩΣ</h4><div class='ex'>ΕΓΩ ΕΙΜΙ ΤΟ ΦΩΣ ΤΟΥ ΚΟΣΜΟΥ. ΚΑΙ Ο ΑΚΟΛΟΥΘΩΝ ΜΟΥ ΟΥΚ ΕΝ ΣΚΟΤΙΑ ΠΕΡΙΠΑΤΗΣΕΙ, ΑΛΛ ΕΧΕΙ ΦΩΣ ΖΩΗΣ.</div>“I am the light of the world: he that followeth me shall not walk in darkness, but shall have the light of life.”",
   "<h4>Walking, not visiting</h4>Peripatēsei is not a stroll — it is the verb of a WAY OF LIFE (like Heb lkh, the walk of Isa 40:31). And akolouthōn — “he who FOLLOWS” — is a participle: following as a habit, not a decision."],
 [ M([['w-grc-akolouthon','he who follows'],['w-grc-peripatēseis','he will walk'],['w-grc-skote','in darkness'],['w-grc-me','me'],['w-grc-exei','he will have'],['w-grc-zoe','life']]),
   MC('σκοτίᾳ (skotíā) in “shall not walk in darkness” is which case?',['dative (of place)','accusative (direct object)','genitive (possession)','nominative (subject)'],0,'The dative does the work of “in” — place by case, not by preposition (here with en).','w-grc-skote'),
   MC('ἀκολούθων — “he that followeth” — is…',['a present participle (ongoing following)','a one-time aorist','an imperative','a noun'],0,'Present participle: the follower keeps following. “Follow” as a way of life, like περιπατέω right beside it.','w-grc-akolouthon'),
   MC('The verb of Isa 40:31’s walk (לָכַך) and Jhn 8:12’s walk share a family in…',['Hebrew lkh + Greek peripateō + akolouthō (to follow)','Greek only','Latin only','Aramaic'],0,'The fam-follow family: walk (Heb/Gk) + follow (Gk) — one movement of life across the languages.','w-grc-peripatēseis'),
   LS('w-grc-akolouthon',['w-grc-akolouthon','w-grc-peripatēseis','w-grc-phos'],'That was ἀκολούθων — “he who follows.”'),
   BD('“he that followeth me shall not walk in darkness”',['w-grc-akolouthon','w-grc-mou','w-grc-mē','w-grc-en','w-grc-skote','w-grc-peripatēseis'],['w-grc-phos','w-grc-exei','w-grc-zoe']),
   VER('v-grc-jhn-8-12') ]),

L('grc-v5','grc-nt','vocab','🫱','Come, Be Rested','Matthew 11:28 & Romans 8:28',
 [ "<h4>ΕΡΧΕΣΘΕ ΠΡΟΣ ΜΕ</h4><div class='ex'>ΕΡΧΕΣΘΕ ΠΡΟΣ ΜΕ ΠΑΝΤΕΣ ΟΙ ΚΟΠΩΝΤΕΣ ΚΑΙ ΠΕΦΟΡΤΙΣΜΕΝΟΙ, ΚΑΙ ΕΓΩ ΑΝΑΠΑΥΣΩ ΥΜΑΣ · ΟΙΔΑΜΕΝ ΟΤΙ ΠΑΝΤΑ ΣΥΝΕΡΓΑΖΕΤΑΙ ΕΙΣ ΑΓΑΘΟΝ</div>“Come unto me, all ye that labour and are heavy laden, and I will give you rest.” — and the engine behind it: “we know that all things work together for good.”",
   "<h4>Two verbs that carry the gospel</h4>Erchesthe — “COME” — an invitation with a direction (pros me, toward me). Anapaussō — “I will give rest” — the aorist of rest: the day’s work, finished. And in Romans the sum: synergazetai, “all things work TOGETHER.”"],
 [ M([['w-grc-erchesthe','come (you pl.)'],['w-grc-kopontes','those who toil'],['w-grc-pherontes','laden; bearing'],['w-grc-zygon','yoke'],['w-grc-praeis','gentle'],['w-grc-anapauso','I will give rest']]),
   MC('πεφορτισμένοι — “heavy laden” — is…',['a perfect passive participle (already loaded)','a present active participle','an aorist imperative','a noun'],0,'Perfect passive: the load is on them already, and it is heavy. The yoke offer comes to people who are already under weight.','w-grc-pherontes'),
   MC('“my yoke is easy” — ζυγόν (zygōn) is…',['the ox-team’s yoke','a crown','a chain','a plow'],0,'The yoke joins the team to the load — and to the driver. Easy yoke: a better team-mate, not no load.','w-grc-zygon'),
   MC('οἴδαμεν (Rom 8:28) “we know” is which tense form?',['perfect — settled knowledge','aorist — one-time past','future — coming','present — now, always'],0,'Perfect of οἶδᾶ: knowledge already banked by experience — not a guess, a possession.','w-grc-oidamen'),
   LS('w-grc-anapauso',['w-grc-anapauso','w-grc-zygon','w-grc-erchesthe'],'That was ἀναπαύσω — “I will give you rest.”'),
   BD('“come unto me, all ye that labour”',['w-grc-erchesthe','w-grc-pros','w-grc-me','w-grc-pas','w-grc-art-ho','w-grc-kopontes'],['w-grc-zygon','w-grc-praeis','w-grc-anapauso']),
   VER('v-grc-mat-11-28'),
   VER('v-grc-rom-8-28') ]),

L('grc-g3','grc-nt','grammar','📐','Articles & Pronouns','ho · hē · to — the signposts of Greek',
 [ "<h4>The article does the pointing</h4>Where English says “the,” Greek hangs the article on the noun: τὸ φῶς — “THE light.” It can carry possession too: μου — “my.” Without articles, Greek would be a language of whispers.",
   "<h4>Three pronoun families</h4>ego (I — me, my), autos (he — him, his), and hymeis (you, plural). The little forms (me, mou, auto, hymas) do enormous work in the Gospels: “come unto ME,” “followeth ME,” “comprehended IT not.”"],
 [ MC('In “τὸ φῶς τοῦ κόσμου,” the word “the” is…',['the article to — neuter nominative','the pronoun autos','the preposition to','the adverb tou'],0,'to — the neuter article: THE light. Then tou, the genitive article: of the world.','w-grc-to'),
   MC('μου (mou) in “followeth ME” is…',['“my” — the genitive of ego (I)','“me” — the accusative','“mine and thine”','the article'],0,'mou = my/mine (genitive of ego); me = me (accusative). One pronoun, two jobs, two forms.','w-grc-mou'),
   MC('In “anapaussō hymas” (Matt 11:28) — “I will give YOU rest” — hymas is…',['you (pl.) — the accusative of hymeis','he (the) — accusative of autos','me — accusative of ego','us — the dative'],0,'hymas — the plural “you” receiving the rest: the invitation lands on the whole crowd, not one person.','w-grc-hymeis'),
   MC('αὐτό (auto) in Jhn 1:5 — “the darkness comprehended IT not” — is…',['it — the neuter of autos','him — the masculine','her — the feminine','they — the plural'],0,'auto — neuter “it”: the light, personified but still a thing the darkness could not hold.','w-grc-auto'),
   M([['w-grc-art-ho','the (masc.)'],['w-grc-art-ti','the (fem.)'],['w-grc-to','the (neut.)'],['w-grc-tou','of the (gen.)'],['w-grc-me','me'],['w-grc-mou','my']]),
   LS('w-grc-mou',['w-grc-mou','w-grc-me','w-grc-auto'],'That was μου — “my.” The smallest pronoun, the closest distance.') ]),

L('grc-g4','grc-nt','grammar','🧭','Prepositions: en · eis · pros','in, into, toward — three doors',
 [ "<h4>Three doors of Greek space</h4>en (+ dative) = IN — you are already there (en skotíā, “in darkness”); eis (+ accusative) = INTO/TO — motion toward a destination (synergazetai eis agathon, “for good”); pros (+ accusative) = TOWARD — the step that closes the distance (erchesthe pros me, “come TO me”).",
   "<h4>The ending tells the door</h4>The preposition names the door; the case-ending tells you who is passing. Dative = arriving where you already are; accusative = moving to meet something. Two cases, three doors, every story in the NT."],
 [ MC('ἐν σκοτίᾳ (en skotíā) — “in darkness” (Jhn 8:12) — en takes…',['the dative (place where)','the accusative (motion)','the genitive (possession)','no case — en is free'],0,'en + dative = the place you are in: in darkness. The dative skotíā is the door-mark.','w-grc-skote'),
   MC('In “panta synergazetai eis agathon” (Rom 8:28), eis means…',['“for” (toward a purpose)','“in” (place)','“against”','“with”'],0,'eis + accusative here points at the DESTINATION: all things are being worked toward good.','w-grc-eis'),
   MC('“Erchesthe pros me” (Matt 11:28) — “come TO me” — pros marks…',['direction toward someone','the place you already stand','possession','time'],0,'pros = the step toward a person: come TOWARD me. The preposition that closes distance.','w-grc-pros'),
   M([['w-grc-en','in; on (place)'],['w-grc-eis','into; toward (motion)'],['w-grc-pros','toward; to (a person)'],['w-grc-skote','darkness (dat.)'],['w-grc-agathon','good (acc.)'],['w-grc-me','me (acc.)']]),
   BD('“come unto me”',['w-grc-erchesthe','w-grc-pros','w-grc-me'],['w-grc-en','w-grc-eis','w-grc-kai']),
   LS('w-grc-en',['w-grc-en','w-grc-eis','w-grc-pros'],'That was ἐν — the word for the place you already occupy.') ]),

L('grc-v6','grc-nt','vocab','🌅','The Risen Lord','Mark 16:9 — the morning of the first day',
 [ "<h4>ΚΑΙ ΓΕΓΟΝΕΝ ΤΩ ΠΡΩΤΩ ΣΑΒΒΑΤΩ…</h4><div class='ex'>Καὶ γεγώνεν τῷ πρωτῷ σαββάτῳ πρωὶ ἀνὲ ἀναστήσασα Ἰησοῦς…</div>“And when Jesus was risen early in the morning on the first day of the week…” (the longer ending, Mark 16:9). The resurrection morning, in one sentence.",
   "<h4>A verb that was done TO</h4>egirethē — “having been RAISED” — is an aorist PASSIVE participle: it did not merely happen; it was done, and it was done once, completely. The stone (hō lithos) is rolled away (anō), and Mary Magdalene is the first named."],
 [ M([['w-grc-egiro','risen; raised'],['w-grc-proi','early; before'],['w-grc-ano','up'],['w-grc-sabbaton','sabbath'],['w-grc-de','and; but'],['w-grc-magdalene','Magdalene']]),
   MC('“having been RAISED” (egirethē) is…',['an aorist passive participle — raised once, completely','a present participle — still rising','an aorist active — he raised himself','a perfect — risen and remaining'],0,'Aorist passive: the raising is a completed act done BY someone else — the Father’s work on the Son.','w-grc-egiro'),
   MC('πρωτῷ (prōtō, “first”) points to…',['the first day after the sabbath','the first person in the crowd','the first stone','the first hour'],0,'tō prōtō sabbatō — “the first day of the week”: the day after the sabbath, the resurrection’s clock.','w-grc-proi'),
   MC('σαββάτῳ (sabbatō) means…',['sabbath — the seventh day','Saturday’s market','the sabbath-keepers only','a feast day'],0,'sabbatōn — the sabbath family: the day of rest, now the marker of the first day. The calendar keeps the story.','w-grc-sabbaton'),
   MC('The first NAMED witness in this verse is…',['Mary Magdalene','Peter','the young man','Joseph'],0,'Maria Magdalēnē — the first name on the resurrection morning. The women are the first witnesses; the names begin with her.','w-grc-magdalene'),
   LS('w-grc-egiro',['w-grc-egiro','w-grc-ano','w-grc-sabbaton'],'That was Ἐγερθεῖσα — “having been raised.”'),
   BD('“when Jesus was risen early in the morning on the first day”',['w-grc-egiro','w-grc-proi','w-grc-ano','w-grc-sabbaton'],['w-grc-magdalene','w-grc-de','w-grc-en']),
   VER('v-grc-mrk-16-9-tr') ]),

L('grc-v7','grc-nt','vocab','⏳','Time: Day, Night, Eternity','hemera · nyx · aiōnios — the long clock',
 [ "<h4>Day, night, and the age to come</h4><div class='ex'>ἡμέρα · νύξ · σάββατον · αἰώνιος</div>Four time-words stretch the Gospel from one morning to the age that does not end: hēmera (day), nyx (night), sabbaton (the sabbath-day), aiōnios (eternal).",
   "<h4>Life on the long clock</h4>“zōē aiōnios” — eternal life — is life measured in AIĒ (ages), not hours. The same word aiōnios that dresses the life of John 3:16 also stretches the sabbath morning of Mark 16 into something that will not set."],
 [ M([['w-grc-hemera','day'],['w-grc-nyx','night'],['w-grc-sabbaton','sabbath'],['w-grc-aiwnios','eternal'],['w-grc-zoe','life'],['w-grc-kosmos','world']]),
   MC('αἰώνιος (aiōnios) in “zōē aiōnios” means…',['eternal — of the age to come','ancient — of long ago','seasonal — of the year','local — of the city'],0,'From aiōn (age): aiōnios = of the age that does not end. “Everlasting life” is life on the long clock.','w-grc-aiwnios'),
   MC('νύξ (nyx, “night”) is the Greek answer to which Hebrew word?',['laylâ (night)','yôm (day)','ʾôr (light)','shĕmaš (sun)'],0,'nyx answers laylâ — the night family across the Testaments: nyx in the Gospels, laylâ in the Psalms.','w-grc-nyx'),
   MC('The morning of Mark 16:9 is marked by…',['sabbaton (the day after) + proi (early)','hemera (daytime)','nyx (night)','aiōnios (eternity)'],0,'tō prōtō sabbatō, prōi anō — the first day after the sabbath, early in the morning: the precise stamp of the resurrection.','w-grc-sabbaton'),
   MC('Which pair is “day / night” in Greek?',['hemera / nyx','zoe / thanatos','aiōn / chronos','kosmos / oikoumenē'],0,'hēmera · nyx — the Greek day/night pair, the same first clock as Hebrew yôm/laylâ.','w-grc-hemera'),
   LS('w-grc-aiwnios',['w-grc-aiwnios','w-grc-zoe','w-grc-hemera'],'That was αἰώνιος — “eternal,” the age that will not set.'),
   BD('“everlasting life”',['w-grc-zoe','w-grc-aiwnios'],['w-grc-hemera','w-grc-nyx','w-grc-kosmos']),
   VER('v-grc-mrk-16-9-tr') ]),

L('grc-v8','grc-nt','vocab','💗','Believe & Live','John 3:16 — the promise clause',
 [ "<h4>…ἵνα πᾶς ὁ πιστεύων…</h4><div class='ex'>ἵνα πᾶς ὁ πιστεύων εἰς αὐτὸν μὴ ἀπόληται ἀλλ᾽ ἔχῃ ζωὴν αἰώνιον.</div>“…that whosoever believeth on him should NOT perish, but HAVE everlasting life.” The second half of the most-quoted verse — a purpose clause built on three verbs.",
   "<h4>The two “nots” of Greek</h4>ou negates what IS; mē negates what MIGHT. Here it is mē — “should not perish” — because the clause is subjunctive, a door kept open: belief is a decision, and the promise waits on it."],
 [ M([['w-grc-pisteuo','believes'],['w-grc-mē','not (subjunctive)'],['w-grc-apollymi','perish'],['w-grc-echo','have'],['w-grc-zoe','life'],['w-grc-aiwnios','eternal']]),
   MC('The “not” in “should not perish” is…',['mē — the subjunctive “not” (a door kept open)','ou — the statement “not”','a double negative','an interjection'],0,'mē belongs to subjunctives: should-not. The promise is a kept-open door, not a statement of fact.','w-grc-mē'),
   MC('ἀπόληται (apollētai, “perish”) is…',['aorist passive of apollymi — “be lost, perish”','present active — “he perishes now”','a noun — “the loss”','a preposition'],0,'apollymi — the loss-verb of the Gospels: to perish, be destroyed. The clause keeps it from happening.','w-grc-apollymi'),
   MC('ἵνα (hina) opens…',['a purpose clause — “in order that”','a question','a command','a time clause'],0,'hina + subjunctive = “so that / in order that”: the WHY of God’s giving. The grammar of purpose.','w-grc-hina'),
   MC('πιστεύων (pisteuōn) — “whosoever believeth” — is…',['a present participle — ongoing believing','an aorist — one past act','an imperative — “believe!”','a noun — “the believer”'],0,'pisteuōn — present participle: belief as a way of walking, not a one-time signature.','w-grc-pisteuo'),
   LS('w-grc-pisteuo',['w-grc-pisteuo','w-grc-zoe','w-grc-echo'],'That was πιστεύων — “the one who believes.”'),
   BD('“should not perish but have everlasting life”',['w-grc-mē','w-grc-apollymi','w-grc-alle','w-grc-echo','w-grc-zoe','w-grc-aiwnios'],['w-grc-pisteuo','w-grc-hina','w-grc-kosmos']),
   VER('v-grc-john-3-16-tr') ]),

L('grc-v9','grc-nt','vocab','👪','Father & Son','pater · huios — the family of God',
 [ "<h4>ὁ θεὸς… τὸν υἱὸν τὸν μονογενῆ…</h4><div class='ex'>ὁ θεὸς οὕτως ἠγάπησεν τὸν κόσμον, ὥστε τὸν υἱὸν τὸν μονογενῆ ἔδωκεν…</div>“For GOD so loved the world, that he gave his ONLY BEGOTTEN SON.” A family sentence: Father, love, giving, Son.",
   "<h4>Word-building</h4>monogenēs = mono (only) + genēs (of origin) — “the only one from his origin.” And the pronoun autos quietly carries “HIS”: the Son is the Father’s own. Greek family grammar is theology."],
 [ M([['w-grc-pater','father'],['w-grc-huios','son'],['w-grc-monogenes','only begotten'],['w-grc-hagapeo','loved'],['w-grc-didomi','gave'],['w-grc-theos','God']]),
   MC('μονογενῆ (monogenēs, “only begotten”) is built from…',['mono (only) + genēs (of origin)','theos (god) + huios (son)','pater (father) + agapē (love)','zōē (life) + aiōn (age)'],0,'mono + genēs: the only one of that origin. The compound does the theology; the dictionary just lists the parts.','w-grc-monogenes'),
   MC('In “his only begotten Son,” “HIS” is carried by…',['the pronoun autos (possessive use)','the article only','a preposition','nothing — Greek has no “his”'],0,'autos doubles as the possessive: his Son. The little pronoun keeps the Father in the sentence.','w-grc-autos'),
   MC('ἠγάπησεν (ēgapēsen, “loved”) in John 3:16 is…',['aorist of agapaō — the deliberate, covenantal love','present — “he loves now”','an adjective — “loving”','a noun — “love”'],0,'agapaō — the love-verb of the NT: choosing love, covenant love. The aorist: one decisive act of the Father.','w-grc-hagapeo'),
   MC('Which pair is “father / son” in Greek?',['pater / huios','theos / logos','kyrios / doulos','pneuma / zōē'],0,'patēr / huios — the family pair that runs from John 3:16 to the Lord’s Prayer (pater hēmōn).','w-grc-pater'),
   LS('w-grc-monogenes',['w-grc-monogenes','w-grc-huios','w-grc-pater'],'That was μονογενῆς — “only begotten.”'),
   BD('“God so loved the world”',['w-grc-theos','w-grc-hagapeo','w-grc-kosmos'],['w-grc-huios','w-grc-didomi','w-grc-monogenes']),
   VER('v-grc-john-1-1-tr') ]),

L('arc-alph','arc','alphabet','א','Script & Alphabet','The square script',
 [ "<h4>One script, two languages</h4>Biblical Aramaic uses the <b>square script</b> — the same letter shapes as Hebrew, written right to left. The difference is in <i>names</i> and a few words: aleph is called “elyph,” shin is “shin,” tav is “taw.”",
   "<h4>Where it lives in the Bible</h4>Native Aramaic appears in Daniel 2:4b–7:28 and Ezra 4:8–6:18 — plus the Aramaic words of Jesus himself in the Gospels."],
 [ M([['ar-elyph','ox'],['ar-beth','house'],['ar-resh','head'],['ar-taw','mark'],['ar-ʿeyn','eye'],['ar-pe','mouth']]),
   MC('Aramaic shares its letter SHAPES with which language?',['Hebrew','Koine Greek','Latin','Punic'],0,'The square (Aramaic) script is exactly what Hebrew adopted — so the two look almost identical on the page.'),
   MC('Which is the Aramaic name of the letter ת?',['taw','tav','teth','taw? no—taw'],0,'In Aramaic it’s “taw”; Hebrew calls it “tav.”'),
   TY('Type the Aramaic name of א',['elyph','aleph'],'elyph'),
   MC('How many letters does the Aramaic alphabet have?',['22','24','26','20'],0,'22 — identical count to Hebrew.') ]),

L('arc-v1','arc','vocab','✝️','The Words of Jesus','Aramaic phrasebook',
 [ "<h4>Jesus spoke Aramaic</h4>The Gospels record Jesus in Aramaic several times — and the Greek text keeps the original sound, untranslated. This phrasebook is the smallest and most precious corner of the Aramaic module.",
   "<h4>Six moments</h4>Mark 5:41 (Talitha koum) · Mark 7:34 (Pethora) · Mark 15:34 (Eli, Eli…) · Mark 14:36 (Abba) · Mark 14:39 (Shta) — the voice beneath the Greek."],
 [ M([['w-arc-talitha','little girl'],['w-arc-qum','arise!'],['w-arc-lemah','why'],['w-arc-abba','father'],['w-arc-ptach','open!'],['w-arc-shta','immediately']]),
   BD('“My God, my God, why have you forsaken me?”',['w-arc-eli','w-arc-eli','w-arc-lemah','w-arc-shavaktni'],['w-arc-abba','w-arc-qum','w-arc-shta']),
   MC('“Talitha koum” (Mark 5:41) means…',['“Little girl, arise!”','“Peace be with you”','“I have fasted forty days”','“Open the door”'],0,'טַלִּיתָא = “little girl” (diminutive of טַלְיָא “little one”); קוּם = “arise!”','w-arc-talitha'),
   MC('Jesus says one Aramaic word to the deaf-mute in Mark 7:34. Which?',['Pethora (Open!)','Talitha (Little girl)','Abba (Father)','Shema (Hear)'],0,'The Greek text preserves it as the strange 9-letter string πεθαθγραμθα — read as פֵּתַח, “open!”','w-arc-ptach'),
   LS('w-arc-abba',['w-arc-abba','w-arc-lemah','w-arc-talitha'],'That was אַבָּא — “Abba,” intimate for “Father.”'),
   MC('“Eli, Eli, lema sabachthani” is the Aramaic of…',['Psalm 22:1 at the cross','the prayer of Solomon','Ezra 4:6','Daniel 2:4'],0,'The cry of the cross — Mark keeps it in Aramaic idiom; Matthew’s ΕΛΟΙ is closer to the Hebrew אֱלֹהִי.','w-arc-eli') ]),

L('arc-g1','arc','grammar','🏛️','Aramaic of the Bible','Daniel 2 & the suffixes',
 [ "<h4>Where Aramaic is native</h4>Bible Aramaic is not a translation — it’s the court language of Babylon: Daniel 2:4b–7:28, the letters of Ezra 4:8–6:18, and a phrase in Ezra 7.",
   "<h4>Absolute state + suffixes</h4>An Aramaic noun stands “absolute” (malkā = “king”), then takes pronominal endings: malkā<sub>kh</sub> = “your (m.) king,” malkān = “my king.” Daniel 2:4 ends מִלִּיךְ — “O king!” (by you, king)."],
 [ MC('Daniel switches from Hebrew to Aramaic at…',['2:4','7:28','4:1','12:4'],0,'Daniel 2:4 begins “Aramaic! (ʼaramāyā)” — and stays in Aramaic until 7:28.'),
   MC('What does אֲרַמַיָּא mean?',['“Aramaic (is being spoken)!”','“The Aramaic people”','“We are Aramaic”','“Aram, the land”'],0,'It flags the language switch — “(From here on) Aramaic!”','w-arc-aramayya'),
   MC('מִלִּיךְ (“O king”) is built from…',['malkā + 2ms suffix','malkā + 1cs suffix','malkā + 3mp suffix','malk + article'],0,'מַלְכָּא “king” + the 2ms possessive = “(O) king (of yours)” — the royal address.','w-arc-milikh'),
   MC('פִּשְׁרָא is an Aramaic word that means…',['“interpretation”','“dream”','“exile”','“kingdom”'],0,'“Interpretation” — its ancestor is the Hebrew פָּשָׁר used in Ps 78:2 and Ps 119:116.','w-arc-pishratam') ]),

L('arc-v2','arc','vocab','👑','King & Kingdom','Daniel 2:44 — the court’s Aramaic',
 [ "<h4>מַלְכָּא → מַלְכוּתָא</h4><div class='ex'>וּבִזְמַן מַלְכֵי יִיחַד אֱלָהָא דִשְׁמַיָּא מַלְכוּתָא וְלָא תִפְרֵץ לְעָלְמָא</div>“And in the days of these kings shall the God of heaven set up a kingdom, which shall never be destroyed.” The Aramaic of the royal court — and the word behind “thy kingdom come.”",
   "<h4>King → Kingdom</h4>malkā (“king”) + a feminine ending = malkhūtā (“kingdom”). One root (מלק) builds both words. In Daniel’s vision the kings of the world share the stage — and the God of heaven brings ONE kingdom."],
 [ M([['w-arc-malka','king'],['w-arc-malkhuta','kingdom'],['w-arc-elaha','God'],['w-arc-shamaya','heaven'],['w-arc-bizman','in the time of'],['w-arc-lelama','forever']]),
   MC('מַלְכוּתָא (“kingdom”) is built from…',['the root מלק (“king”) + a feminine ending','the word šamaya (“heaven”)','a separate root meaning “reign”','the Hebrew word for “city”'],0,'malkā (king) → malkhūtā (kingdom): same root, one ending. “Thy kingdom come” is Aramaic malkhūtkā.','w-arc-malkhuta'),
   MC('דִּי (dī) in “אֱלָהָא דִשְׁמַיָּא” means…',['of (“the God of heaven”)','and','not','therefore'],0,'dī is Aramaic’s possessive/relative particle — “the God OF heaven,” “a kingdom THAT …”','w-arc-di'),
   MC('יִיחַד (yiḥaḏ) — “shall set up” — is from…',['יָחַד “to be one, to join”','מָלַךְ “to reign”','יָשַׁב “to sit”','יָדַע “to know”'],0,'“Set up a kingdom” literally means “make one / join”: the kingdom of God is a making-one.','w-arc-yikhud'),
   MC('וְלָא תִפְרֵץ — “which shall not be destroyed” — the negation לָא is…',['the Aramaic “not” (kin of Hebrew lōʾ)','a preposition “to”','the word “no,” used only in oaths','a relative particle'],0,'lā — the Aramaic “not.” The kingdom that shall not be broken: forever, lelama.','w-arc-lo'),
   BD('“the God of heaven set up a kingdom”',['w-arc-elaha','w-arc-di','w-arc-shamaya','w-arc-yikhud','w-arc-malkhuta'],['w-arc-bizman','w-arc-malka','w-arc-we']),
   VER('v-arc-dan-2-44'),
   TREE('v-arc-dan-2-44') ]),

L('arc-v3','arc','vocab','🔥','God of Gods','Daniel 2:47 & 3:25 — the court & the furnace',
 [ "<h4>אֱלָהָךְ דֵּי אֱלָהִין</h4><div class='ex'>אֱלָהָךְ דֵּי אֱלָהִין מַלְכָּא דִמַּלְכָּא · חָזֵית שְׁבַע אֱנָשׁוֹהַת בְּתוֹךְ נָרוּ</div>“Thy God is God of gods, and Lord of kings” — the king’s own confession. And the vision beside it: “I saw seven men… in the midst of the fire.”",
   "<h4>Six men, seven</h4>Three friends bound (enash), and the furnace doing its work (nar). But Daniel’s eyes count seven — the fourth, “like a son of the gods” (ilahin), walking in the MIDDLE (btôk) of it. The fire had company."],
 [ M([['w-arc-ilahin','gods'],['w-arc-elaha','God'],['w-arc-malka','king; kings'],['w-arc-chazet','I saw'],['w-arc-shab','seven'],['w-arc-naru','fire']]),
   MC('אֱלָהִין (ilahin) — “God of gods” — is…',['the plural of elāhā “God”','a different word for “angels”','the dual of “two gods”','a title only for idols'],0,'ilahin = the plural of elāhā. “God of gods” is Aramaic’s superlative: the God above every god, even above the gods of the kings.','w-arc-ilahin'),
   MC('חָזֵית (ḥāzēṯ) — “I saw” — is…',['Qal perfect 1cs (a past, done-seeing)','imperfect (habitual)','an imperative “look!”','a participle'],0,'Perfect, 1cs: Daniel’s eyewitness formula. The court reports visions; Daniel reports seeing.','w-arc-chazet'),
   MC('בְּתוֹךְ (btôk) — the fourth man walked…',['in the MIDDLE of the fire','above the fire','around the fire’s rim','outside, calling in'],0,'btôk = “in the midst of”: not above the trial, not around it — inside it, walking.','w-arc-btuch'),
   LS('w-arc-naru',['w-arc-naru','w-arc-enash','w-arc-shab'],'That was נָרוּ — the fire. The furnace was doing its work.'),
   BD('“thy God is God of gods”',['w-arc-elaha','w-arc-di','w-arc-ilahin'],['w-arc-malka','w-arc-chazet','w-arc-shab']),
   VER('v-arc-dan-2-47'),
   VER('v-arc-dan-3-25'),
   TREE('v-arc-dan-2-47') ]),

L('arc-v4','arc','vocab','📜','The Aramaic Creation','Daniel 2:4 — the creation verse in the court tongue',
 [ "<h4>וְעַתָּא אַרְמַיְיָא</h4><div class='ex'>אַרְמַיְיָא · בְּרֵישָׁא בָרָא אֱלָהָא שְׁמַיָּא וְאַרְעָא</div>“Aramaic!” From Daniel 2:4 the Old Testament speaks in the language of the court — and Daniel quotes the creation verse in it: “In the beginning God created the heavens and the earth.”",
   "<h4>Two tongues, one verse</h4>bĕrēšîṯ (Heb) → bĕrēšā (Aram); šĕmayim (Heb) → šmayā; ʾereṣ (Heb) → ʾarʿāyā. The same creation, restated in the empire’s tongue: even the world’s beginning had to pass through the court’s language."],
 [ M([['w-arc-aramayya','Aramaic-speaking'],['w-arc-bresha','in the beginning'],['w-arc-bara','created'],['w-arc-shamaya','heaven'],['w-arc-areea','earth'],['w-arc-we','and']]),
   MC('בְּרֵישָׁא (bĕrēšā, “in the beginning”) is the Aramaic of…',['Hebrew bĕrēšîṯ — the same root','a word for “royal court”','the name of a king','a legal term “first clause”'],0,'bĕrēšā answers bĕrēšîṯ: the beginning, in the court tongue. Creation keeps its first words in both languages.','w-arc-bresha'),
   MC('“Aramaic!” (aramayya) marks…',['the language switch in Daniel — from Hebrew to the court tongue','a greeting to the king','a prayer formula','a trade term'],0,'From Daniel 2:4 on, the OT speaks Aramaic: the empire’s language takes over the story — including a restated creation verse.','w-arc-aramayya'),
   MC('Which pair is the Aramaic of Hebrew “heavens and earth”?',['šmayā (shamaya) + ʾarʿāyā (areea) / šĕmayim + ʾereṣ','šĕmayim + ʾereṣ (both Hebrew)','šmayā + bavel','arʿāyā + šereh'],0,'shamaya/areea — the Aramaic pair for šĕmayim/ʾereṣ: heaven (singular in Aramaic) and earth, the world’s two addresses.','w-arc-shamaya'),
   MC('The creation verb in BOTH tongues is…',['bara — created (same root)','kĕrun — to speak','malak — to rule','yikhaḏ — to unite'],0,'bara — the root of creation, unchanged from Hebrew to Aramaic: the act of creating outlasts the switch of tongues.','w-arc-bara'),
   LS('w-arc-bresha',['w-arc-bresha','w-arc-aramayya','w-arc-shamaya'],'That was בְּרֵישָׁא — “in the beginning,” in the court tongue.'),
   BD('“in the beginning God created heaven and earth”',['w-arc-bresha','w-arc-bara','w-arc-shamaya','w-arc-we','w-arc-areea'],['w-arc-aramayya','w-arc-malka','w-arc-di']),
   VER('v-arc-dan-2-4') ]),

L('arc-v5','arc','vocab','📯','The King’s Decree','Ezra 4:6 — shereh and bavel',
 [ "<h4>The memo that moved an empire</h4><div class='ex'>…וְשֶׁרֶה… בָּבֶל…</div>Ezra 4:6 is a memorandum in the imperial tongue: the shereh (the decree, the order) and the verb bavel — “to destroy.” The empire runs on two words: the order, and the threat.",
   "<h4>The breaking-root</h4>bavel belongs to the same breaking family as the Hebrew parats (the tiferetz of Dan 2:44 — “which shall NOT be destroyed”): empires break things; the kingdom of God does not break."],
 [ M([['w-arc-shereh','decree; order'],['w-arc-bavel','to destroy'],['w-arc-we','and'],['w-arc-di','of; that'],['w-arc-malka','king'],['w-arc-bizman','in the time of']]),
   MC('שֶׁרֶה (shereh, “decree”) is…',['the legal term for a royal order','a name for Jerusalem','a temple item','a greeting'],0,'shereh — the decree: the word the empire writes with. In Ezra 4 it is the instrument the officials brandish.','w-arc-shereh'),
   MC('בָּבֶל (bavel, “to destroy”) shares its breaking-family with…',['Hebrew parats — the tiferetz of Dan 2:44','Hebrew berakhah — blessing','Aramaic bĕrēšā — beginning','Hebrew berit — covenant'],0,'bavel / parats — the break-through family. The kingdoms break (tiferetz, Dan 2:44); the kingdom of God is the one that does not.','w-arc-bavel'),
   MC('In Dan 2:44 the kingdom “shall NOT be destroyed” — the negation is…',['lā (the Aramaic “not”)','dī (of; that)','we (and)','kĕ (like)'],0,'wĕlā tiferetz — “and shall not be broken”: the lā that no shereh in the world can cancel.','w-arc-lo'),
   LS('w-arc-bavel',['w-arc-bavel','w-arc-shereh','w-arc-malka'],'That was בָּבֶל — “to destroy,” the word the empires keep coming back to.'),
   BD('“the God of heaven set up a kingdom”',['w-arc-elaha','w-arc-di','w-arc-shamaya','w-arc-yikhud','w-arc-malkhuta'],['w-arc-shereh','w-arc-bavel','w-arc-bizman']),
   VER('v-arc-ezr-4-6') ]),

L('arc-v6','arc','vocab','🌙','Dreams & Their Deciphering','chalmei · pishratam — the dream and its meaning',
 [ "<h4>הַחֲלָמִים וְהַפִּשְׁרָתָם</h4><div class='ex'>…חֲלָמִים וְהַפִּשְׁרָתָם… מִלִּיךְ</div>“Now then, tell us the DREAM, and its INTERPRETATION, O KING!” (Dan 2:4). The king names the dream (chalmei) and its deciphering (pishratam) — and the interpreters answer that the meaning came to US (lanu) from God.",
   "<h4>The suffix does the pointing</h4>pishratAM — “its interpretation”: the ending -am is the possessive “its.” Aramaic wears its pronouns as coats on the end of the nouns."],
 [ M([['w-arc-chalmei','dreams'],['w-arc-pishratam','its interpretation'],['w-arc-gigiddid','were revealed; told'],['w-arc-lanu','to us'],['w-arc-milikh','O king!'],['w-arc-hineh','behold']]),
   MC('חֲלָמֵי (ḥalmei, “dreams”) is…',['the plural of “dream” (the -ei plural)','a singular “one dream”','a verb “to sleep”','a place name'],0,'ḥalm + -ei: the dreams, plural — the king has more than one to test with. The -ei ending is the Aramaic plural marker.','w-arc-chalmei'),
   MC('מִלִּיךְ (milikh) is…',['the vocative “O king!”','a past verb “he reigned”','a noun “the crown”','a preposition'],0,'milikh — the cry of the court: “O king!” The מלק root again — the same root as malkā (king) and malkhūtā (kingdom).','w-arc-milikh'),
   MC('The ending in pishratAM (“its interpretation”) means…',['“its” — the possessive suffix','-am = “for us”','a plural marker','a question mark'],0,'The -am coat on the noun: the interpretation OF IT — of that dream. Aramaic puts the owner on the end of the word.','w-arc-pishratam'),
   MC('“The interpretation came to US” — the “us” is…',['lanu (the dative of we — “to us”)','milikh (O king)','shereh (decree)','bavel (destroy)'],0,'lanu — “to us”: the dative of the we-family. The sages’ answer: the meaning did not come from them, it came TO them.','w-arc-lanu'),
   LS('w-arc-chalmei',['w-arc-chalmei','w-arc-pishratam','w-arc-milikh'],'That was חֲלָמֵי — “the dreams,” the king’s test.'),
   BD('“the dream and its interpretation, O king”',['w-arc-chalmei','w-arc-pishratam','w-arc-milikh'],['w-arc-lanu','w-arc-gigiddid','w-arc-hineh']),
   VER('v-arc-dan-2-4') ]),

L('arc-g2','arc','grammar','🔗','Particles: di · we · btuch','the glue words of Aramaic',
 [ "<h4>Four little words carry the story</h4>di (“of; that”) is the relative/possessive particle — “the God OF heaven,” “a kingdom THAT shall not break”; we (“and”) is the great conjunction; btôk (“in the midst of”) places the fourth man INSIDE the fire; and lelama (“forever”) is the Aramaic of Hebrew ʿôlām.",
   "<h4>One family of “forever”</h4>ʿôlām (Heb) · ləʿălmā (Aram) — the same horizon in two tongues: the kingdom that shall not be broken is lelama, and the love of the Psalms is ʿôlām. The fam-olam family."],
 [ MC('דִּי (dī) in “אֱלָהָא דִשְׁמַיָּא” means…',['“of” — the God OF heaven','“and”','“not”','“therefore”'],0,'dī — the workhorse particle: possession (“of”) and relation (“that”). Almost every clause in Daniel wears it.','w-arc-di'),
   MC('בְּתוֹךְ (btôk) — the fourth man walked…',['IN THE MIDST of the fire','above it','around its edge','outside, watching'],0,'btôk — “in the midst of”: not above the trial, not around it. Inside it, walking (Dan 3:25).','w-arc-btuch'),
   MC('לְעָלְמָא (ləʿălmā, “forever”) is the Aramaic family-member of…',['Hebrew ʿôlām (the fam-olam family)','Hebrew ʿad (until)','Aramaic dī (of)','Hebrew ʾaḥărîṯ (end)'],0,'ʿôlām / ləʿălmā — “forever” in two tongues: the kingdom that breaks no other, forever.','w-arc-lelama'),
   M([['w-arc-di','of; that'],['w-arc-we','and'],['w-arc-btuch','in the midst of'],['w-arc-ata','you (2ms)'],['w-arc-chad','one; single'],['w-arc-lelama','forever']]),
   BD('“the God of heaven”',['w-arc-elaha','w-arc-di','w-arc-shamaya'],['w-arc-malka','w-arc-btuch','w-arc-lelama']),
   LS('w-arc-di',['w-arc-di','w-arc-we','w-arc-btuch'],'That was דִי — the particle that ties one name to another.') ]),

L('arc-v7','arc','vocab','🌍','Heaven & Earth in Two Tongues','shamaya & ar’aya vs. shamayim & ʾarets',
 [ "<h4>The world’s language switch</h4><div class='ex'>שְׁמַיָּא וְאַרְעָא (Aram) · הַשָּׁמַיִם וְהָאָרֶץ (Heb)</div>The Old Testament switches from Hebrew to Aramaic at Daniel 2:4 — and with it, heaven and earth change their dress: šĕmayim → šmayā, ʾereṣ → ʾarʿāyā. One world, two address books.",
   "<h4>What changes, what doesn’t</h4>The spellings change; the theology does not. The creator verb stays bĕrēšā/bara in both; the names of heaven and earth bend to the new tongue. The world keeps its meaning through the switch."],
 [ M([['w-heb-shamayim','šĕmayim — heavens (Heb)'],['w-arc-shamaya','šmayā — heaven (Aram)'],['w-heb-aretz','ʾereṣ — earth (Heb)'],['w-arc-areea','ʾarʿāyā — earth (Aram)'],['w-heb-reshit','bĕrēšîṯ — beginning (Heb)'],['w-arc-bresha','bĕrēšā — beginning (Aram)']]),
   MC('The Old Testament switches to Aramaic at…',['Daniel 2:4 — the court demands the dream in “Aramaic!”','Genesis 1:1','Exodus 20:1','Psalm 1'],0,'Daniel 2:4 is the hinge: from the court scene onward the OT speaks the empire’s tongue — until Ezra’s letter continues it.','w-arc-aramayya'),
   MC('Which creation verb SURVIVES the language switch unchanged?',['bara — created','yĕhî — “let there be”','rāʾâ — saw','yāḥal — to be strong'],0,'bara keeps its root across both tongues: the act of creating is the one word the switch does not touch.','w-arc-bara'),
   MC('Aramaic “heaven” is singular (šmayā) where Hebrew is…',['plural — šĕmayim, “heavens”','also singular','dual','an adjective'],0,'šĕmayim — the Hebrew plural of appellation (“heavens”); šmayā — the Aramaic singular. The same sky, counted differently.','w-arc-shamaya'),
   LS('w-arc-areea',['w-arc-areea','w-heb-aretz','w-arc-shamaya'],'That was אַרְעָא — “earth,” in the court tongue.'),
   BD('“heaven and earth” (Aramaic)',['w-arc-shamaya','w-arc-we','w-arc-areea'],['w-arc-bresha','w-arc-aramayya','w-arc-malka']),
   VER('v-arc-dan-2-4'),
   VER('v-heb-gen-1-1') ]),

L('lat-alph','lat','alphabet','✠','Script & Alphabet','Church Latin sounds',
 [ "<h4>One alphabet, one pronunciation</h4>The Latin alphabet is the one your keyboard uses. Ecclesiastical (Church) Latin has a few rules that make it sound Italian-adjacent.",
   "<h4>The sound rules</h4><b>c</b> before e/i = “ch” (centum → CHENT-um). <b>v</b> = “w” (Vulgate → WUL-gate). <b>h</b> is always silent. Double consonants are both pronounced (pāscit → PAAS-chit)."],
 [ M([['la-c','k / ch'],['la-v','w'],['la-h','silent'],['la-x','ks'],['la-z','ts'],['la-q','k (before u)']]),
   MC('In “centum,” the c says…',['“ch” (tʃ)','“k”','“s”','nothing'],0,'Before e/i, c softens to “ch” — the same rule you already know from English “century.”'),
   MC('The letter v in Church Latin sounds like…',['w','v (as in “very”)','f','b'],0,'V is pronounced “w” — VERBUM is chanted “ver-boom.” That is the Church-Latin ear.','w-lat-verbum'),
   TY('Type the Latin letter that is ALWAYS silent in ecclesiastical pronunciation',['h'],'h'),
   MC('Which word keeps its consonant cluster tight in Church Latin?',['pāscit (paas-chit)','vita (VEE-ta)','lux (LOOKS)','pax (PAKS)'],0,'pāscit — the sc cluster plus the long ā: “PAAS-chit.” Church Latin keeps its clusters and doubles sounded.') ]),

L('lat-v1','lat','vocab','📜','The Beginning','John 1:1 in Vulgate Latin',
 [ "<h4>IN PRINCIPIO ERAT VERBUM</h4><div class='ex'>In principio erat verbum, et verbum erat apud Deum, et Deus erat verbum.</div>Jerome’s Vulgate — the Bible of the Latin West for 1,500 years. Note: it says <b>“the Word was with (apud) God”</b>, and the final <b>Deus</b> has no article — Latin has none at all.",
   "<h4>Word order</h4>Latin puts the verb where it wants: <i>creāvit Deus caelum et terram</i> (“created God heaven and earth” — subject last, weight on the object)."],
 [ M([['w-lat-verbum','word'],['w-lat-deus','God'],['w-lat-principium','beginning'],['w-lat-sum','to be (was)'],['w-lat-apud','with']]),
   BD('“In the beginning was the Word”',['w-lat-in','w-lat-principium','w-lat-sum','w-lat-verbum'],['w-lat-deus','w-lat-et','w-lat-apud']),
   MC('PRINCIPIO is in which case?',['Ablative','Accusative','Genitive','Nominative'],0,'The ablative of prīncipium — Latin marks “in the beginning” with the case, not a separate preposition word… (in + ablative here).','w-lat-principium'),
   MC('“The Word was with God” uses which preposition for “with”?',['apud (+ acc.)','in (+ abl.)','ab (+ abl.)','per (+ acc.)'],0,'APUD DEUM — apud + accusative = “in the company of.” Jerome’s exact word for πρὸς τὸν θεόν.','w-lat-apud'),
   LS('w-lat-verbum',['w-lat-verbum','w-lat-lux','w-lat-pax'],'That was VERBUM — “the Word.”') ]),

L('lat-v2','lat','vocab','💗','The Love','John 3:16 in Vulgate Latin',
 [ "<h4>SIC ENIM DILEXIT DEUS MUNDUM</h4><div class='ex'>Sic enim dilexit Deus mundum, ut Filium suum unigenitum dedit, ut omnis qui credit in eum non pereat, sed habeat vitam aeternam.</div>“For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.”",
   "<h4>ut … -et</h4>The purpose clause is the Latin signature: <b>ut</b> + subjunctive. <i>ut non pereat, sed habeat</i> — “that he may not perish, but may have.”"],
 [ M([['w-lat-diligo','loved'],['w-lat-mundus','world'],['w-lat-filius','son'],['w-lat-credo','believes'],['w-lat-vita','life'],['w-lat-aeternus','eternal']]),
   BD('“he gave his only begotten Son”',['w-lat-dare','w-lat-suus','w-lat-unigenitus','w-lat-filius'],['w-lat-diligo','w-lat-mundus','w-lat-et']),
   MC('CREDIT (whosoever believeth) is which form?',['Perfect with present force','Present indicative','Aorist','Future'],0,'The Latin perfect can read as present: “whosoever believeth.” (Jerome’s rendering of πιστεύων.)','w-lat-credo'),
   MC('PEREAT and HABEAT are…',['present subjunctives of purpose (after ut)','perfect verbs','imperfects','infinitives'],0,'ut … non pereat, sed habeat — “that he may not perish, but may have.” The subjunctive marks purpose.','w-lat-perire'),
   MC('AETERNAM agrees with which word?',['vitam (fem. acc. sg.)','filius (masc. nom.)','mundum (masc. acc.)','Deus (masc. nom.)'],0,'aeternam = feminine accusative singular — it dresses up vitam like a matching adjective.') ]),

L('lat-g1','lat','grammar','📐','Cases & Tenses','From Psalm 23 & John 1',
 [ "<h4>Cases carry the sentence</h4><b>DEUS</b> (nom.) does the loving; <b>MUNDUM</b> (acc.) is loved; <b>PRINCIPIO</b> (abl.) is “in the beginning”; <b>DEUM</b> (acc.) is who the Word was with. The ending tells you the job.",
   "<h4>Three tenses to start</h4>Present (pāscit “he shepherds” — now, continually), imperfect (erat “was”), perfect (creāvit “he created” — once, done), future (deerit “shall be lacking”)."],
 [ MC('DEUM (John 1:1) is which case?',['Accusative','Nominative','Ablative','Genitive'],0,'-um marks the masculine/neuter accusative of the 2nd declension — “the Word was with GOD.”','w-lat-deus'),
   MC('PASCIT in “Dominus pascit me” is…',['present indicative 3sg (“he shepherds”)','perfect 3sg','future 3sg','imperfect 3sg'],0,'Present, 3sg — the Shepherd’s care is ongoing: “The LORD shepherds me (now, always).”','w-lat-pascere'),
   MC('DEERIT (“I shall not want”) is which tense?',['Future','Perfect','Present','Imperfect'],0,'Future of dēesse: “it shall be lacking.” The Shepherd’s promise is forward-looking.','w-lat-deesse'),
   MC('AETERNAM (John 3:16) is…',['feminine accusative singular','masculine nominative singular','neuter ablative','feminine genitive'],0,'It must match vitam: fem. acc. sg. — “eternal life” = vitam aeternam.') ]),

L('lat-v3','lat','vocab','🐏','The Shepherd','Psalm 23:2 in the Vulgate',
 [ "<h4>IN PASCUIS … PASCET</h4><div class='ex'>In pascuis, ubi habitat me, pascet; super aquam quietis, ibi me convertet.</div>“He maketh me to lie down in green pastures: he leadeth me beside the still waters.” The shepherd-verb appears twice — pascuus (pastures) and pascet (he shall feed) — from one root, pāscere.",
   "<h4>Adverbs place the scene</h4>UBI (“where”) opens the first clause; IBI (“there”) opens the second. One adverb pair draws the whole picture: WHERE he makes me dwell, THERE he refreshes me."],
 [ M([['w-lat-pascuus','pastures'],['w-lat-ubi','where'],['w-lat-habitat','he dwells'],['w-lat-pascet','he shall feed'],['w-lat-super','upon; beside'],['w-lat-convertet','he shall refresh']]),
   MC('PASCUIS (“in green pastures”) is…',['ablative plural of pāscuus','nominative singular','accusative plural','genitive singular'],0,'-is marks the ablative plural — the case of location: “IN pastures.”','w-lat-pascuus'),
   MC('PASCET (“he shall feed”) is which tense?',['future (the -et ending)','present','perfect','imperfect'],0,'pāscet — future 3sg: the shepherd’s promise looks forward.','w-lat-pascet'),
   MC('UBI and IBI are…',['adverbs: “where” and “there”','prepositions','nouns (“water,” “rest”)','conjunctions'],0,'ubi = where (the place in question); ibi = there (that place). Two little words carry the whole scene.','w-lat-ubi'),
   MC('QUIETIS (“of stillness”) is which case?',['genitive','ablative','accusative','dative'],0,'quiētis is the genitive of quietēs “stillness” — “water OF stillness” (aquam quietis); the genitive dresses the noun.','w-lat-quietus'),
   BD('“beside the still waters he refreshes me”',['w-lat-super','w-lat-aqua','w-lat-quietus','w-lat-mi','w-lat-convertet'],['w-lat-ubi','w-lat-pascet','w-lat-et']),
   VER('v-lat-ps-23-2'),
   TREE('v-lat-ps-23-2') ]),

L('lat-v4','lat','vocab','⚖️','I Shall Not Want','Psalm 23:1 & 119:105 — three tongues, one promise',
 [ "<h4>DOMINUS PASCIT ME</h4><div class='ex'>Dominus pascit me; nihil mihi deerit · Lumen pedibus meis verbum tuum; et lux semitae meae.</div>“The LORD is my shepherd; I shall not want. A lamp unto my feet is thy word; and a light unto my path.”",
   "<h4>One verse, three witnesses</h4>The same promise in Hebrew, LXX, and Vulgate: rōʿî (Heb) · poimainei me (LXX) · pascit me (Lat) — SHEPHERDS. And “I shall not want”: echsar · ouden husterēso · nihil deerit — the fam-lack family, in three tongues. The light of Ps 119:105: nēr · lampas · lumen/lux."],
 [ M([['w-lat-dominus','the LORD'],['w-lat-pascere','he feeds'],['w-lat-deesse','shall be lacking'],['w-lat-nihil','nothing'],['w-lat-lumen','light'],['w-lat-semita','path']]),
   MC('nihil mihi deerit — “I shall not want” — the structure is…',['subject + dative + future verb','accusative + nominative + present','two nouns, no verb','a command'],0,'nihil (nothing) is the subject; mihi (to me) is dative; deerit is future: “nothing shall be lacking to me.”','w-lat-deesse'),
   MC('Which is the LXX “I shall lack nothing”?',['ouden husterēso','poimainei me','kyrios me','phōs zeōs'],0,'ouden = “nothing,” husterēso = “I shall lack” — the LXX of אֶחְסָר, and of the Vulgate’s deerit: one family of “not lacking.”','w-lxx-hestereso'),
   MC('LUMEN (Ps 119:105) belongs to the same light-family as…',['Hebrew ʾôr + Greek phōs (fam-lux)','Hebrew shalom + Greek eirēnē','Hebrew ruach + Greek pneuma','Aramaic shamaya + Greek ouranos'],0,'Lumen and lux are kin (r-lat-lux); the fam-lux family: ʾôr · phōs · lux/lumen — and the lamps ner · lampas beside them.','w-lat-lumen'),
   MC('SEMITAE (“unto my path”) is which case?',['genitive','dative','ablative','accusative'],0,'semitae = genitive of semita “path” — “a light of my path” (lux semitae meae).','w-lat-semita'),
   LS('w-lat-pascere',['w-lat-pascere','w-lxx-poimainei','w-lat-dominus'],'That was PASCIT — “he feeds.” The Vulgate’s shepherd.'),
   BD('“the LORD is my shepherd; I shall not want”',['w-lat-dominus','w-lat-pascere','w-lat-mi','w-lat-nihil','w-lat-mi','w-lat-deesse'],['w-lat-lumen','w-lat-semita','w-lat-tuus']),
   VER('v-lat-ps-23-1'),
   VER('v-lxx-ps-23-1'),
   VER('v-lat-ps-119-105'),
   TREE('v-lat-ps-23-1') ]),

L('lat-g2','lat','grammar','⏭️','The Future: -et','pascet · convertet · deerit — the coming promise',
 [ "<h4>Four tenses, four endings</h4>Present: pāscit (he feeds, now); imperfect: erat (it was, in process); perfect: creāvit (he created, done and kept); future: pāscet (he SHALL feed). The ending carries the time — no helper verbs, no “will.”",
   "<h4>The Shepherd’s futures</h4>Psalm 23 runs forward on the -et: pāscet (he shall feed), convertet (he shall refresh), deerit (it shall be lacking — in negation: nihil mihi deerit, “I shall not want”). The Shepherd’s promises are all in the future tense, and all are kept."],
 [ MC('PASCET (“he shall feed”) is…',['future — the -et ending','present — the -it ending','perfect — the -it with a prefix','imperfect — the -bat ending'],0,'pāscere → pāscet: the future 3sg. The promise looks forward: he SHALL feed you in green pastures.','w-lat-pascet'),
   MC('DEERIT in “nihil mihi deerit” (Ps 23:1) is…',['“it shall be lacking” — the future of dēesse','the present — “it lacks now”','a noun — “the lack”','a command — “lack!”'],0,'dēesse → deerit: the future. And the negation around it: NOTHING shall be lacking TO ME.','w-lat-deesse'),
   MC('CONVERTET (Ps 23:2) “he shall refresh” is which tense?',['future (the -et ending)','present','perfect','imperfect'],0,'convertere → convertet: the future of turning/restoring. The refreshment is promised, then given.','w-lat-convertet'),
   MC('Which is the IMperfect (in-process past) of the four?',['erat — “it was” (John 1:1)','creāvit — “he created” (perfect)','pāscet — “he shall feed” (future)','fūit — not in our data'],0,'erat — the imperfect: the Word WAS in process of being, at the beginning. The tense of the ongoing past.','w-lat-sum'),
   M([['w-lat-pascet','he shall feed (fut.)'],['w-lat-convertet','he shall refresh (fut.)'],['w-lat-deesse','it shall be lacking (fut.)'],['w-lat-pascere','he feeds (pres.)'],['w-lat-creo','I create (pres.)'],['w-lat-sum','was (imperf.)']]),
   LS('w-lat-pascet',['w-lat-pascet','w-lat-convertet','w-lat-deesse'],'That was PASCET — the Shepherd’s promise, in the future tense.'),
   BD('“he shall feed me in green pastures”',['w-lat-pascet','w-lat-mi','w-lat-pascuus'],['w-lat-convertet','w-lat-deesse','w-lat-ubi']) ]),

L('lat-g3','lat','grammar','🧭','Prepositions: in · super · apud','the cases they ride with',
 [ "<h4>Three prepositions, three jobs</h4>in (+ ablative) marks the PLACE you are in — “in pascuis” (in green pastures); super (+ accusative) rides OVER/BESIDE — “super aquam quietis” (beside the still waters); apud (+ accusative) keeps COMPANY with — “apud deum” (with God).",
   "<h4>The ending tells the case</h4>The preposition names the job; the case-ending shows it being done: -is (ablative) for the place, -um (accusative) for the object. In + ablative, super + accusative, apud + accusative — the three doors of Latin space."],
 [ MC('“IN pascuis” (Ps 23:2) — in takes…',['the ablative (the place you are in)','the accusative (motion)','the genitive (possession)','no case — in is free'],0,'in + ablative = the place: IN pastures. The -is ending of pascūis is the ablative door-mark.','w-lat-in'),
   MC('“super aquam quietis” (beside the still waters) — super takes…',['the accusative (aquam)','the ablative (aquae)','the genitive (aquae)','the dative'],0,'super + accusative: OVER/beside. AQUAM — the -um ending: the object the preposition rides toward.','w-lat-super'),
   MC('“APUD deum” (John 1:1, “with God”) — apud takes…',['the accusative (deum)','the ablative','the genitive','the dative'],0,'apud + accusative = “in the company of”: the Word was WITH God — apud deum. Jerome’s exact word for πρὸς τὸν θεόν.','w-lat-apud'),
   M([['w-lat-in','in; on (place)'],['w-lat-super','upon; beside'],['w-lat-apud','with (in company of)'],['w-lat-pascuus','pastures (abl.)'],['w-lat-aqua','water (acc.)'],['w-lat-deus','God (acc.)']]),
   BD('“the Word was with God”',['w-lat-verbum','w-lat-apud','w-lat-deus'],['w-lat-in','w-lat-super','w-lat-et']),
   LS('w-lat-super',['w-lat-super','w-lat-in','w-lat-apud'],'That was SUPER — “upon, beside” — the preposition of the still waters.') ]),

L('lat-v5','lat','vocab','📖','The Word in Three Tongues','davar · logos · verbum — the word that holds the world',
 [ "<h4>One idea, three languages</h4><div class='ex'>דָּבָר · λόγος · VERBUM</div>The “word” that carries the world wears three names: dāḇār (Hebrew — “your word is a lamp unto my feet,” Ps 119:105), logos (Greek — “in the beginning was the Word,” Jhn 1:1), and verbum (Latin — “in principio erat verbum”).",
   "<h4>The lamp stays a lamp</h4>Psalm 119:105 travels the same road: nēr (Heb) → lampas (LXX) → lumen/lux (Vulgate). The word that is a lamp in Hebrew is a torch in Greek and a light in Latin — one light-family, three dressings."],
 [ M([['w-heb-davar','dāḇār — word (Heb)'],['w-grc-logos','logos — word (Gk)'],['w-lat-verbum','verbum — word (Lat)'],['w-heb-ner','nēr — lamp (Heb)'],['w-lxx-lampe','lampas — torch (Gk LXX)'],['w-lat-lumen','lumen — light (Lat)']]),
   MC('The LXX rendering of dāḇār (Ps 119:105) is…',['logos — “word”','phōs — “light”','pneuma — “spirit”','sōphía — “wisdom”'],0,'The LXX answers dāḇār with logos — the same word John opens with. The translation made the connection official.','w-grc-logos'),
   MC('“In principio erat verbum” — the Vulgate of John 1:1 — has “word” as…',['verbum (neuter)','logos (Greek)','dāḇār (Hebrew)','scriptura (writing)'],0,'verbum — the Latin “word”: Jerome’s rendering of logos, and the heir of dāḇār across the whole Bible.','w-lat-verbum'),
   MC('The lamp of Ps 119:105 in the LXX is…',['lampas (the torch)','phōs (the light only)','kyríos (the Lord)','zōē (life)'],0,'lampas — the Greek torch, the LXX of nēr: the lamp that walks ahead of the feet, in Greek dress.','w-lxx-lampe'),
   LS('w-lat-verbum',['w-lat-verbum','w-grc-logos','w-heb-davar'],'That was VERBUM — the word, in the language of the Church.'),
   BD('“your word is a lamp unto my feet” (Hebrew)',['w-heb-davar','w-heb-ner','w-heb-l','w-heb-rgal'],['w-lat-verbum','w-lat-lumen','w-lat-pedes']),
   VER('v-lat-john-1-1'),
   VER('v-heb-ps-119-105') ]),

L('lat-v6','lat','vocab','💗','Love: Diligo, Amo, Caritas','the two love-verbs and the noun',
 [ "<h4>Two verbs, one noun</h4><div class='ex'>dīligō · amō · caritās</div>Latin has two love-verbs: dīligere — to CHOOSE to love (the deliberate, covenantal love of “Deus mundum dīligit”), and amāre — to love tenderly, warmly. And the noun caritās — charity, love in the giving sense (the love of 1 Cor 13).",
   "<h4>The grammar of choosing</h4>dīligere is the verb of election: God did not merely feel warmth toward the world — he CHOSE to love it, and the choosing cost a Son. The aorist of the Gospels wears the same shape: one decisive act."],
 [ M([['w-lat-diligo','loved (chose to love)'],['w-lat-amo','to love (tenderly)'],['w-lat-caritas','charity; love'],['w-lat-mundus','world'],['w-lat-deus','God'],['w-lat-vita','life']]),
   MC('The verb of “Deus mundum dīligit” is…',['dīligere — the deliberate, choosing love','amāre — the tender love','volere — to will','credere — to believe'],0,'dīligere — the love that chooses: God did not passively feel toward the world; he chose it, and the choosing had a cost.','w-lat-diligo'),
   MC('caritās is…',['the NOUN — love/charity (the love of 1 Cor 13)','a verb — “to love”','an adjective — “loving”','a place name'],0,'caritās — the noun: love as a thing you have and give. The caritas of the Pauline letters: love in the giving sense.','w-lat-caritas'),
   MC('Which pair is “tender love / choosing love”?',['amō / dīligō','caritās / grātia','fides / spes','dīligō / dīlit'],0,'amāre — the warm, tender love; dīligere — the love that chooses and commits. Latin keeps both; the Gospel needs both.','w-lat-amo'),
   LS('w-lat-caritas',['w-lat-caritas','w-lat-diligo','w-lat-amo'],'That was CARITAS — love with its hands open.'),
   BD('“God so loved the world”',['w-lat-deus','w-lat-diligo','w-lat-mundus'],['w-lat-caritas','w-lat-amo','w-lat-vita']),
   VER('v-lat-john-3-16') ]),

L('lat-v7','lat','vocab','🕊️','Faith & Grace','fides · grātia · crēdō — the Pauline pair in Latin',
 [ "<h4>Three words carry the Gospel</h4><div class='ex'>fīdes · grātia · crēdō</div>The noun fīdes (faith), the verb crēdō (I believe), and the gift that precedes both: grātia (grace). “Whosoever believeth in him” — omnis qui crēdit in eum — is the faith-verb in motion.",
   "<h4>Grace first</h4>grātia is the word that opens the door before fides walks through it: not earned, not reached — given. The Vulgate keeps the Pauline pair intact: faith as the noun, crēdere as the verb, grace as the ground."],
 [ M([['w-lat-fides','faith'],['w-lat-credo','I believe'],['w-lat-gratia','grace'],['w-lat-deus','God'],['w-lat-pater','father'],['w-lat-spiritus','spirit']]),
   MC('fīdes is…',['the NOUN — faith (the Vulgate of Greek pistis)','a verb — “to believe”','an adjective — “faithful”','a preposition'],0,'fīdes — the noun: faith as a possession and a posture. The Greek pistis wears this coat in the Vulgate.','w-lat-fides'),
   MC('crēdo in “whosoever BELIEVETH” (John 3:16) is…',['the verb — “to believe, trust”','the noun — “the belief”','an adjective — “believing”','an interjection'],0,'crēdere — the faith-verb: omnis qui crēdit in eum — “whosoever BELIEVETH in him.” The verb that fīdes is made of.','w-lat-credo'),
   MC('grātia (“grace”) in the Pauline pair is…',['the gift that precedes faith','the result of faith','a human effort','a temple offering'],0,'grātia — the ground before the walk: not earned, not reached — given. Grace first, then the faith that meets it.','w-lat-gratia'),
   MC('Which trio is “faith, believe, grace”?',['fīdes / crēdō / grātia','caritās / amō / dīligō','fīlius / pater / grātia','spēs / fīdes / crēdō'],0,'fīdes · crēdō · grātia — the noun, the verb, and the ground: the Pauline pair with its foundation.','w-lat-fides'),
   LS('w-lat-credo',['w-lat-credo','w-lat-fides','w-lat-gratia'],'That was CRĒDO — “I believe,” the verb of the whole chapter.'),
   BD('“whosoever believeth in him”',['w-lat-omnis','w-lat-qui','w-lat-credo','w-lat-in','w-lat-eum'],['w-lat-fides','w-lat-gratia','w-lat-deus']),
   VER('v-lat-john-3-16') ])
];

/* ---------- path per language (order of the learning path, §5) ---------- */
var LABELS = {
  'heb-alph':'Alphabet','heb-v1':'Genesis 1:1','heb-v2':'Light','heb-v3':'Chaos','heb-v4':'Shepherd','heb-v5':'Light','heb-v6':'Eagles','heb-g3':'Vowels','heb-g4':'Little Words','heb-g5':'Stems','heb-v7':'Vision','heb-v8':'One Root','heb-v9':'Day & Night','heb-g1':'Nouns','heb-g2':'Verbs',
  'grc-alph':'Alphabet','grc-v1':'John 1:1','grc-v2':'John 3:16','grc-v3':'Light of the World','grc-v4':'Light','grc-v5':'Rest','grc-g3':'Articles','grc-g4':'Prepositions','grc-v6':'Risen','grc-v7':'Time','grc-v8':'Believe','grc-v9':'Father & Son','grc-g1':'Cases','grc-g2':'Tenses',
  'arc-alph':'Alphabet','arc-v1':'Phrasebook','arc-v2':'Kingdom','arc-v3':'God of Gods','arc-v4':'Creation','arc-v5':'Decree','arc-v6':'Dreams','arc-g2':'Particles','arc-v7':'Two Tongues','arc-g1':'Daniel 2',
  'lat-alph':'Alphabet','lat-v1':'John 1:1','lat-v2':'John 3:16','lat-v3':'Shepherd','lat-v4':'Not Want','lat-g2':'Future','lat-g3':'Prepositions','lat-v5':'The Word','lat-v6':'Love','lat-v7':'Faith & Grace','lat-g1':'Cases & Tenses'
};
function pathFor(lang){
  var les = LESSONS.filter(function(l){ return l.lang === lang; });
  var nodes = [];
  les.forEach(function(l){ nodes.push({ kind:'lesson', id:l.id, icon:l.icon, label:LABELS[l.id] || l.title.split(' ')[0], title:l.title }); });
  nodes.push({ kind:'verse', id:'verse-'+lang, icon:'📖', label:'Verses', title:'Verse-by-Verse Study' });
  nodes.push({ kind:'parse', id:'parse-'+lang, icon:'🧩', label:'Parsing', title:'Interactive Verse Parsing' });
  nodes.push({ kind:'quiz', id:'quiz-'+lang, icon:'🎯', label:'Quiz', title:'Auto-generated Quiz' });
  nodes.push({ kind:'srs', id:'srs-'+lang, icon:'🔁', label:'Review', title:'Spaced-repetition Review' });
  return nodes;
}
function lessonById(id){
  for (var i=0;i<LESSONS.length;i++) if (LESSONS[i].id === id) return LESSONS[i];
  return null;
}
function versesForLang(lang){
  var list = [];
  Object.keys(DB.Verses).forEach(function(vid){
    var v = DB.Verses[vid];
    if (v.language_code === lang) list.push(v);
  });
  /* group by book+ch:vn, keep first source per group but remember siblings */
  var seen = {};
  var out = [];
  list.sort(function(a,b){ return a.book_id.localeCompare(b.book_id) || a.chapter - b.chapter || a.verse_num - b.verse_num; }).forEach(function(v){
    var k = v.book_id+'-'+v.chapter+':'+v.verse_num;
    if (!seen[k]){ seen[k] = true; v._refs = DB.verseRefs(v.verse_id); out.push(v); }
  });
  return out;
}

window.LESSONS = LESSONS;
window.PATH = { pathFor:pathFor, lessonById:lessonById, versesForLang:versesForLang };
})();
